/**
 * Generated by tsnapi — public API snapshot of `@unocss/extractor-mdc`
 */
// #region Default Export
declare function _default(): Extractor;
export default _default
// #endregion

// #region Referenced (internal)
interface Extractor {
  name: string;
  order?: number;
  extract?: (_: ExtractorContext) => Awaitable<Set<string> | CountableSet<string> | string[] | undefined | void>;
}
// #endregion