/**
 * Generated by tsnapi — public API snapshot of `@unocss/inspector/devframe`
 */
// #region Interfaces
export interface StandaloneInspectorOptions {
  root?: string;
  config?: UserConfig | string;
  defaults?: UserConfigDefaults;
  patterns?: string[];
}
export interface UnocssInspectorDevframe {
  definition: DevframeDefinition;
  notifyModuleUpdated: (_: ModuleUpdate) => void;
  notifyConfigChanged: () => void;
  notifyInvalidated: () => void;
}
// #endregion

// #region Types
export type InspectorServerFunctions = ReturnType<typeof createRpcFunctions>;
// #endregion

// #region Functions
export declare function createInspectorDevframe(_: UnocssPluginContext): UnocssInspectorDevframe;
export declare function createRpcFunctions(_: UnocssPluginContext): readonly [import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"get-project-info", "query", [], Promise<ProjectInfo>, undefined, undefined, undefined>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"get-module-info", "query", [string], Promise<ModuleInfo | null> | null, undefined, undefined, undefined>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"generate-repl", "query", [input: string, includeSafelist: boolean], Promise<ReplResult>, undefined, undefined, undefined>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"get-overview", "query", [], Promise<OverviewInfo>, undefined, undefined, undefined>];
export declare function createStandaloneInspectorDevframe(_?: StandaloneInspectorOptions): Promise<UnocssInspectorDevframe>;
// #endregion

// #region Variables
export declare const INSPECTOR_RPC_SCOPE: string;
// #endregion