import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Navbar from '../components/navbar'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next App with unocss</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Navbar />

      <main className="py-20 px-12 text-center flex flex-col items-center gap-20px font-sans">
        <span text="blue 5xl hover:red" cursor="default">Hello Next</span>
        <div className="i-carbon-car inline-block" text="4xl teal-500" />

        <Link href="/blog">
          <a className="flex items-center btn">
            Blog
            <div className="i-carbon-arrow-right" />
          </a>
        </Link>
      </main>
    </>
  )
}

export default Home
