/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-tagify`
 */
// #region Interfaces
export interface TagifyOptions {
  prefix?: string;
  excludedTags?: (string | RegExp)[];
  extraProperties?: Record<string, string> | ((_: string) => Partial<Record<string, string>>);
  defaultExtractor?: boolean;
}
// #endregion

// #region Functions
export declare function extractorTagify(_: TagifyOptions): Extractor;
export declare function variantTagify(_: TagifyOptions): VariantObject;
// #endregion

// #region Variables
export declare const htmlTagRE: RegExp;
export declare const MARKER: string;
export declare const presetTagify: import("@unocss/core").PresetFactory<object, TagifyOptions>;
// #endregion

// #region Default Export
declare const _default: import("@unocss/core").PresetFactory<object, TagifyOptions>;
export default _default
// #endregion