/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-web-fonts`
 */
// #region Interfaces
export interface Axes {
  default: string;
  min: string;
  max: string;
  step: string;
}
export interface Provider {
  name: WebFontsProviders;
  getPreflight?: (_: WebFontMeta[], _: (_: string) => Promise<any>) => Awaitable<string | undefined>;
  getImportUrl?: (_: WebFontMeta[]) => string | undefined;
  getFontName?: (_: WebFontMeta) => string;
}
export interface ResolvedWebFontMeta extends Omit<WebFontMeta, 'provider'> {
  provider: Provider;
}
export interface WebFontMeta {
  name: string;
  weights?: (string | number)[];
  italic?: boolean;
  widths?: (string | number)[];
  variable?: Record<string, Partial<Axes>>;
  subsets?: string[];
  preferStatic?: boolean;
  provider?: WebFontsProviders;
}
export interface WebFontProcessor {
  getCSS?: (_: ResolvedWebFontMeta[], _: Provider[], _: (_: ResolvedWebFontMeta[], _: Provider[]) => Awaitable<string>) => Awaitable<string | undefined>;
  transformCSS?: (_: string) => Promise<string | undefined>;
}
export interface WebFontsOptions {
  provider?: WebFontsProviders;
  fonts?: Record<string, WebFontMeta | string | (WebFontMeta | string)[]>;
  extendTheme?: boolean;
  themeKey?: string;
  inlineImports?: boolean;
  customFetch?: (_: string) => Promise<any>;
  processors?: Arrayable<WebFontProcessor>;
  timeouts?: false | {
    warning?: number;
    failure?: number;
  };
}
// #endregion

// #region Types
export type WebFontsProviders = 'google' | 'bunny' | 'fontshare' | 'fontsource' | 'coollabs' | 'zeoseven' | 'none' | Provider;
// #endregion

// #region Functions
export declare function createGoogleProvider(_: WebFontsProviders, _: string): Provider;
export declare function normalizedFontMeta(_: WebFontMeta | string, _: WebFontsProviders): ResolvedWebFontMeta;
// #endregion

// #region Variables
export declare const presetWebFonts: import("@unocss/core").PresetFactory<any, WebFontsOptions>;
export declare const ZeoSevenFontsProvider: Provider;
// #endregion

// #region Default Export
declare const _default: import("@unocss/core").PresetFactory<any, WebFontsOptions>;
export default _default
// #endregion