/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-web-fonts/local`
 */
// #region Interfaces
export interface LocalFontProcessorOptions {
  cwd?: string;
  cacheDir?: string;
  fontAssetsDir?: string;
  fontServeBaseUrl?: string;
  fetch?: typeof fetch;
  onDownload?: (_: string, _: Buffer) => void | Promise<void>;
}
// #endregion

// #region Functions
export declare function createLocalFontProcessor(_?: LocalFontProcessorOptions): WebFontProcessor;
// #endregion