
export const presetWindiTargets: string[] = [
  // tables
  'border-collapse',
  'border-separate',
  // object-position
  'object-center',
  'object-ct',
  'object-cb',
  // divide
  'divide',
  'divide-y-4',
  'divide-x-4',
  'divide-x-reverse',
  'divide-green-500',
  'divide-opacity-50',
  'divide-dashed',
  'divide-dotted',
  'divide-transparent',
  'divide-current',
  // backdrop filters
  'backdrop-filter',
  'backdrop-blur',
  'backdrop-blur-md',
  'backdrop-blur-4',
  'backdrop-brightness-0',
  'backdrop-brightness-60',
  'backdrop-contrast-125',
  'backdrop-grayscale',
  'backdrop-grayscale-90',
  'backdrop-hue-rotate-0',
  'backdrop-hue-rotate-360',
  '-backdrop-hue-rotate-90',
  'backdrop-invert',
  'backdrop-invert-90',
  'backdrop-saturate',
  'backdrop-saturate-30',
  'backdrop-sepia',
  'backdrop-sepia-80',
  'line-clamp-7',
  'line-clamp-100',
  'line-clamp-none',
  // isolation
  'isolate',
  'isolate-auto',
  // filters
  'filter',
  'blur',
  'blur-md',
  'blur-4',
  'brightness-0',
  'brightness-60',
  'contrast-125',
  'drop-shadow',
  'drop-shadow-[0_4px_3px_#000]',
  'drop-shadow-none',
  'drop-shadow-md',
  'grayscale',
  'grayscale-90',
  'hue-rotate-0',
  'hue-rotate-360',
  '-hue-rotate-90',
  'invert',
  'invert-90',
  'saturate',
  'saturate-30',
  'sepia',
  'sepia-80',
  // animation
  'animate-none',
  '!animate-ping',
  'animate-pulse',
  'animate-pulse-alt',
  'hover:animate-bounce',
  'animate-300',
  'animate-100s',
  'animate-duration-100',
  'animate-duration-100.32',
  'animate-delay--1.37',
  'animate-speed-$speed',
  'animate-name-move',
  'animate-play-paused',
  'animate-normal',
  'animate-play-state-running',
  'animate-mode-none',
  'animate-fill-mode-both',
  'animate-direction-alternate-reverse',
  'animate-count-2.4',
  'animate-iteration-count-2',
  'animate-iteration-count-2-4-infinity',
]
