export const presetMiniTargets: string[] = [
  // border
  'border-[#124]',
  'border-[2em]',
  'border-[calc(1em-1px)]',
  'border-4',
  'border-black/10',
  'border-blue',
  'border-red-100',
  'border-red-200/10',
  'border-red-300/20',
  'border-red100',
  'border-red2',
  'border-[var(--color)]',
  'border-b',
  'border-x',
  'border-green-100/20',
  'border-t-2',
  'border-y-red',
  'border-x-[rgb(1,2,3)]/[0.5]',
  'border',
  'border-$color',
  'border-t-$color',
  'border-x-$color',
  'rounded-[4px]',
  'rounded-1/2',
  'rounded-full',
  'rounded-md',
  'rounded-rb-1/2',
  'rounded-t-sm',
  'rounded-tr',
  'rounded',

  // size
  'h-auto',
  'h-1',
  'h-21',
  'h-1/4',
  'h-lg',
  'w-auto',
  'w-1',
  'w-21',
  'w-1/4',
  'w-lg',
  'max-h-[1px]',
  'max-w-none',
  'max-w-20',
  'max-w-lg',
  'max-w-full',
  'max-w-$var',
  'max-w-screen-lg',
  'min-h-[1px]',
  'min-w-none',
  'min-w-20',
  'min-w-lg',
  'min-w-full',
  'min-w-$var',
  'min-w-screen-lg',
  'h-$var',
  'h-[calc(1000px-4rem)]',
  'w-[calc(calc(100px*10)-4rem)]',

  // background
  'bg-[#153]/10',
  'bg-[#1533]',
  'bg-[#1533]/10',
  'bg-[rgba(1,2,3,0.5)]',
  'bg-#452233/40',
  'bg-red-100',
  'bg-teal-100/55',
  'bg-teal-200:55',
  'bg-teal-300:[.55]',
  'bg-teal-400/[.55]',
  'bg-teal-500/[55%]',

  // decoration
  'decoration-none',
  'decoration-transparent',
  'decoration-purple/50',
  'underline',
  'underline-dashed',
  'underline-red-500',
  'underline-op80',
  'underline-auto',
  'underline-5',
  'underline-1rem',
  'underline-offset-auto',
  'underline-offset-4',
  'underline-offset-0.6rem',

  // transforms
  'transform',
  'transform-gpu',
  'transform-cpu',
  'transform-none',
  'translate-y-1/4',
  '-translate-y-1/2',
  'translate-y-px',
  'translate-full',
  '-translate-full',
  'translate-x-full',
  '-translate-x-full',
  'hover:translate-x-3',
  'peer-checked:translate-x-[var(--reveal)]',
  'before:translate-y-full',
  'rotate-1deg',
  '-rotate-2',
  'rotate-[var(--spin)]',
  'active:scale-4',
  'preserve-3d',
  'preserve-flat',

  // grid
  'grid-cols-$1',
  'grid-cols-[1fr,2fr,100px,min-content]',
  'grid-cols-2',
  'grid-rows-[1fr,2fr,100px,min-content]',
  'grid-rows-3',
  'grid',
  'auto-rows-min',
  'auto-rows-fr',
  'row-auto',
  'row-span-[hi]',
  'row-[span_1/span_2]',
  'auto-cols-auto',
  'auto-rows-auto',
  'col-span-1',
  'row-span-full',
  'row-end-1',
  'row-start-full',
  'auto-flow-cols-dense',
  'grid-cols-minmax-1rem',
  'grid-rows-minmax-100px',

  // transition
  'transition-none',
  'transition-delay-300',
  'transition-duration-300',
  'transition-property-width',
  'transition-property-all',
  'transition-200',
  'transition',

  // transition-timing-function
  'ease-linear',
]
