/**
 * Generated by tsnapi — public API snapshot of `@unocss/config`
 */
// #region Functions
export declare function createRecoveryConfigLoader<U extends UserConfig>(): (_?: string, _?: string | U, _?: LoadConfigSource[], _?: UserConfigDefaults) => Promise<LoadConfigResult<U>>;
export declare function loadConfig<U extends UserConfig>(_?: string, _?: string | U, _?: LoadConfigSource[], _?: UserConfigDefaults): Promise<LoadConfigResult<U>>;
// #endregion

// #region Other
export { LoadConfigResult }
export { LoadConfigSource }
// #endregion