import { defineConfig } from 'tsdown'

export default defineConfig([
  {
    name: 'Dual',
    entry: [
      'src/webpack.ts',
      'src/postcss.ts',
    ],
    clean: true,
    dts: true,
    format: ['esm', 'cjs'],
    external: [
      '@unocss/webpack',
      '@unocss/postcss',
    ],
    failOnWarn: false,
  },
  {
    name: 'ESM only',
    entry: [
      'src/index.ts',
      'src/vite.ts',
      'src/astro.ts',
      'src/preset-uno.ts',
      'src/preset-icons.ts',
      'src/preset-attributify.ts',
      'src/preset-tagify.ts',
      'src/preset-web-fonts.ts',
      'src/preset-typography.ts',
      'src/preset-wind.ts',
      'src/preset-mini.ts',
      'src/preset-wind3.ts',
      'src/preset-wind4.ts',
    ],
    clean: false,
    dts: true,
    external: [
      '@unocss/core',
      '@unocss/astro',
      '@unocss/postcss',
      '@unocss/preset-attributify',
      '@unocss/preset-icons',
      '@unocss/preset-mini',
      '@unocss/preset-tagify',
      '@unocss/preset-typography',
      '@unocss/preset-uno',
      '@unocss/preset-web-fonts',
      '@unocss/preset-wind',
      '@unocss/preset-wind3',
      '@unocss/preset-wind4',
      '@unocss/transformer-attributify-jsx',
      '@unocss/transformer-compile-class',
      '@unocss/transformer-directives',
      '@unocss/transformer-variant-group',
    ],
    attw: {
      profile: 'esm-only',
    },
  },
])
