/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-typography`
 */
// #region Interfaces
export interface TypographyColorScheme {
  'body'?: Arrayable<string | number>;
  'headings'?: Arrayable<string | number>;
  'lead'?: Arrayable<string | number>;
  'links'?: Arrayable<string | number>;
  'bold'?: Arrayable<string | number>;
  'counters'?: Arrayable<string | number>;
  'bullets'?: Arrayable<string | number>;
  'hr'?: Arrayable<string | number>;
  'quotes'?: Arrayable<string | number>;
  'quote-borders'?: Arrayable<string | number>;
  'captions'?: Arrayable<string | number>;
  'kbd'?: Arrayable<string | number>;
  'kbd-shadows'?: Arrayable<string | number>;
  'code'?: Arrayable<string | number>;
  'pre-code'?: Arrayable<string | number>;
  'pre-bg'?: Arrayable<string | number>;
  'th-borders'?: Arrayable<string | number>;
  'td-borders'?: Arrayable<string | number>;
}
export interface TypographyCompatibilityOptions {
  noColonWhere?: boolean;
  noColonIs?: boolean;
  noColonNot?: boolean;
}
export interface TypographyCSSObject extends Record<string, CSSObject | string | number> {}
export interface TypographyOptions<T extends TypographyTheme = TypographyTheme> {
  selectorName?: string;
  cssExtend?: TypographyCSSObject | ((_: T) => TypographyCSSObject);
  compatibility?: TypographyCompatibilityOptions;
  important?: boolean | string;
  colorScheme?: TypographyColorScheme;
  sizeScheme?: TypographySizeScheme;
  cssVarPrefix?: string;
}
export interface TypographySizeScheme extends Record<string, TypographyCSSObject> {}
export interface TypographyTheme {
  colors?: Record<string, any>;
}
// #endregion

// #region Variables
export declare const presetTypography: <Theme extends TypographyTheme = TypographyTheme>(options?: TypographyOptions<Theme> | undefined) => Preset<Theme>;
// #endregion

// #region Default Export
declare const _default: <Theme extends TypographyTheme = TypographyTheme>(options?: TypographyOptions<Theme> | undefined) => Preset<Theme>;
export default _default
// #endregion