packages:
  - bench
  - bench/fixtures/*
  - docs
  - playground
  - interactive
  - packages-engine/*
  - packages-integrations/*
  - packages-presets/*
  - packages-deprecated/*
  - virtual-shared/*
  - test/fixtures/*
catalog:
  '@ampproject/remapping': ^2.3.0
  '@antfu/eslint-config': ^4.14.1
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@arethetypeswrong/cli': ^0.17.4
  '@babel/core': ^7.27.4
  '@babel/plugin-syntax-jsx': ^7.27.1
  '@babel/preset-typescript': ^7.27.1
  '@codemirror/lang-css': ^6.3.1
  '@codemirror/lang-html': ^6.4.9
  '@codemirror/lang-javascript': ^6.2.4
  '@codemirror/lang-xml': ^6.1.0
  '@csstools/normalize.css': ^12.1.1
  '@iconify-json/carbon': ^1.2.9
  '@iconify-json/iconoir': ^1.2.7
  '@iconify-json/la': ^1.2.1
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/tabler': ^1.2.19
  '@iconify-json/teenyicons': ^1.2.2
  '@iconify-json/twemoji': ^1.2.2
  '@iconify-json/uim': ^1.2.3
  '@iconify-json/vscode-icons': ^1.2.22
  '@iconify/types': ^2.0.0
  '@iconify/utils': ^2.3.0
  '@nuxt/kit': ^3.17.5
  '@nuxt/schema': ^3.17.5
  '@shikijs/markdown-it': ^3.6.0
  '@shikijs/vitepress-twoslash': ^3.6.0
  '@sveltejs/kit': ^2.21.4
  '@types/connect': ^3.4.38
  '@types/css-tree': ^2.3.10
  '@types/fs-extra': ^11.0.4
  '@types/js-yaml': ^4.0.9
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/node': ^24.0.1
  '@types/prettier': ^2.7.3
  '@types/pug': ^2.0.10
  '@types/react': ^18.3.23
  '@types/splitpanes': ^2.2.6
  '@types/webpack': ^5.28.5
  '@types/webpack-sources': ^3.2.3
  '@types/ws': ^8.18.1
  '@typescript-eslint/utils': ^8.34.0
  '@vitejs/plugin-legacy': ^6.1.1
  '@vitejs/plugin-vue': ^5.2.4
  '@vitest/ui': ^3.2.3
  '@vue/reactivity': ^3.5.16
  '@vueuse/core': ^13.3.0
  '@vueuse/math': ^13.3.0
  '@vueuse/nuxt': ^13.3.0
  astro: ^4.16.18
  autoprefixer: ^10.4.21
  brotli-size: ^4.0.0
  bumpp: ^10.1.1
  cac: ^6.7.14
  chokidar: ^3.6.0
  codemirror: ^6.0.1
  codemirror-theme-vars: ^0.1.2
  colorette: ^2.0.20
  consola: ^3.4.2
  core-js: ^3.43.0
  cross-env: ^7.0.3
  css-tree: ^3.1.0
  eslint: ^9.28.0
  eslint-plugin-antfu: ^3.1.1
  eslint-vitest-rule-tester: ^2.2.0
  esno: ^4.8.0
  execa: ^9.6.0
  find-up: ^6.3.0
  floating-vue: ^5.2.2
  fs-extra: ^11.3.0
  fuse.js: ^7.1.0
  fzf: ^0.5.2
  gzip-size: ^6.0.0
  jiti: ^2.4.2
  js-yaml: ^4.1.0
  jsdom: ^26.1.0
  knitwork: ^1.2.0
  lint-staged: ^16.1.0
  local-pkg: ^1.1.1
  lru-cache: ^11.1.0
  lz-string: ^1.5.0
  magic-string: ^0.30.17
  markdown-it-link-attributes: ^4.0.1
  msw: ^2.7.0
  npm-run-path: ^6.0.0
  nuxt: ^3.17.5
  nuxt-tsconfig-stub: ^0.0.2
  ofetch: ^1.4.1
  p-limit: ^6.2.0
  pathe: ^2.0.3
  perfect-debounce: ^1.0.0
  pnpm: ^10.12.1
  postcss: ^8.5.5
  postcss-nested: ^7.0.2
  prettier: ^2.8.8
  prettier-plugin-svelte: ^2.10.1
  pug: ^3.0.3
  react: ^18.3.1
  rimraf: ^6.0.1
  rollup: ^4.43.0
  sanitize.css: ^13.0.0
  semver: ^7.7.2
  shiki: ^3.6.0
  simple-git: ^3.28.0
  simple-git-hooks: ^2.13.0
  sirv: ^3.0.1
  splitpanes: ^4.0.4
  std-env: ^3.9.0
  svelte: ^5.34.1
  svelte-eslint-parser: ^1.2.0
  synckit: ^0.11.8
  tailwindcss: ^3.4.17
  taze: ^19.1.0
  terser: ^5.42.0
  theme-vitesse: ^0.8.3
  tinyglobby: ^0.2.14
  tsup: ^8.5.0
  tsx: ^4.20.2
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unconfig: ^7.3.2
  unplugin: ^2.3.5
  unplugin-auto-import: ^19.3.0
  unplugin-utils: ^0.2.4
  unplugin-vue-components: ^28.7.0
  unplugin-vue-markdown: ^28.3.1
  vite: ^6.3.5
  vite-plugin-inspect: ^11.1.0
  vite-plugin-pages: ^0.32.5
  vite-plugin-windicss: ^1.9.4
  vitepress: ^1.6.3
  vitepress-plugin-group-icons: ^1.6.0
  vitest: ^3.2.3
  vue: ^3.5.16
  vue-eslint-parser: ^10.1.3
  vue-flow-layout: ^0.1.1
  vue-router: ^4.5.1
  vue-virtual-scroller: ^2.0.0-beta.8
  webpack: ^5.99.9
  webpack-sources: ^3.3.2
  windicss: ^3.5.6
