packages:
  - bench
  - bench/fixtures/*
  - docs
  - playground
  - interactive
  - packages-engine/*
  - packages-integrations/*
  - packages-presets/*
  - packages-deprecated/*
  - virtual-shared/*
  - test/fixtures/*
overrides:
  is-arguments: npm:@nolyfill/is-arguments@^1.0.44
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  is-generator-function: npm:@nolyfill/is-generator-function@^1.0.44
  is-regex: npm:@nolyfill/is-regex@^1.0.44
  is-typed-array: npm:@nolyfill/is-typed-array@^1.0.44
  object.assign: npm:@nolyfill/object.assign@^1.0.44
  side-channel: npm:@nolyfill/side-channel@^1.0.44
  which-typed-array: npm:@nolyfill/which-typed-array@^1.0.44

catalogs:
  babel:
    '@babel/parser': ^7.28.0
    '@babel/traverse': ^7.28.0

  build:
    '@ampproject/remapping': ^2.3.0
    brotli-size: ^4.0.0
    bumpp: ^10.2.0
    gzip-size: ^6.0.0
    rollup: ^4.44.2
    terser: ^5.43.1
    unbuild: ^3.5.0
    webpack: ^5.99.9
    webpack-sources: ^3.3.3

  css:
    '@codemirror/lang-css': ^6.3.1
    '@csstools/normalize.css': ^12.1.1
    autoprefixer: ^10.4.21
    css-tree: ^3.1.0
    postcss: ^8.5.6
    postcss-nested: ^7.0.2
    sanitize.css: ^13.0.0
    tailwindcss: ^3.4.17
    windicss: ^3.5.6

  docs:
    '@codemirror/lang-html': ^6.4.9
    '@codemirror/lang-javascript': ^6.2.4
    '@codemirror/lang-xml': ^6.1.0
    '@shikijs/markdown-it': ^3.7.0
    '@shikijs/vitepress-twoslash': ^3.7.0
    codemirror: ^6.0.1
    codemirror-theme-vars: ^0.1.2
    markdown-it-link-attributes: ^4.0.1
    pug: ^3.0.3
    shiki: ^3.7.0
    theme-vitesse: ^0.8.3
    vitepress: ^1.6.3
    vitepress-plugin-group-icons: ^1.6.1

  eslint:
    '@antfu/eslint-config': ^4.16.2
    eslint: ^9.30.1
    eslint-plugin-antfu: ^3.1.1
    eslint-vitest-rule-tester: ^2.2.0
    svelte-eslint-parser: ^1.2.0

  frameworks:
    astro: ^4.16.18
    core-js: ^3.43.0
    react: ^18.3.1

  icons:
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/iconoir': ^1.2.7
    '@iconify-json/la': ^1.2.1
    '@iconify-json/logos': ^1.2.4
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/tabler': ^1.2.19
    '@iconify-json/teenyicons': ^1.2.2
    '@iconify-json/twemoji': ^1.2.2
    '@iconify-json/uim': ^1.2.3
    '@iconify-json/vscode-icons': ^1.2.23
    '@iconify/types': ^2.0.0
    '@iconify/utils': ^2.3.0

  nuxt:
    '@nuxt/kit': ^3.17.6
    '@nuxt/schema': ^3.17.6
    nuxt: ^3.17.6
    nuxt-tsconfig-stub: ^0.0.2

  svelte:
    '@sveltejs/kit': ^2.22.2
    prettier-plugin-svelte: ^2.10.1
    svelte: ^5.35.2

  testing:
    '@vitest/ui': ^3.2.4
    jsdom: ^26.1.0
    msw: ^2.7.0
    vitest: ^3.2.4

  types:
    '@types/connect': ^3.4.38
    '@types/css-tree': ^2.3.10
    '@types/fs-extra': ^11.0.4
    '@types/js-yaml': ^4.0.9
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^24.0.10
    '@types/prettier': ^2.7.3
    '@types/pug': ^2.0.10
    '@types/react': ^18.3.23
    '@types/splitpanes': ^2.2.6
    '@types/webpack': ^5.28.5
    '@types/webpack-sources': ^3.2.3
    '@types/ws': ^8.18.1

  typescript:
    '@typescript-eslint/utils': ^8.35.1
    '@typescript/native-preview': latest
    tsup: ^8.5.0
    tsx: ^4.20.3
    typescript: ^5.8.3

  utils:
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    '@arethetypeswrong/cli': ^0.17.4
    acorn: ^8.15.0
    cac: ^6.7.14
    chokidar: ^3.6.0
    colorette: ^2.0.20
    consola: ^3.4.2
    cross-env: ^7.0.3
    esno: ^4.8.0
    execa: ^9.6.0
    find-up: ^6.3.0
    fs-extra: ^11.3.0
    fuse.js: ^7.1.0
    fzf: ^0.5.2
    jiti: ^2.4.2
    js-yaml: ^4.1.0
    knitwork: ^1.2.0
    lint-staged: ^16.1.2
    local-pkg: ^1.1.1
    lru-cache: ^11.1.0
    lz-string: ^1.5.0
    magic-string: ^0.30.17
    npm-run-path: ^6.0.0
    ofetch: ^1.4.1
    p-limit: ^6.2.0
    pathe: ^2.0.3
    perfect-debounce: ^1.0.0
    pnpm: ^10.12.4
    premove: ^4.0.0
    prettier: ^2.8.8
    semver: ^7.7.2
    simple-git: ^3.28.0
    simple-git-hooks: ^2.13.0
    sirv: ^3.0.1
    splitpanes: ^4.0.4
    std-env: ^3.9.0
    synckit: ^0.11.8
    taze: ^19.1.0
    tinyglobby: ^0.2.14
    unconfig: ^7.3.2
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-utils: ^0.2.4
    zimmerframe: ^1.1.2

  vite:
    '@vitejs/plugin-legacy': ^6.1.1
    '@vitejs/plugin-vue': ^5.2.4
    vite: ^7.0.2
    vite-plugin-inspect: ^11.3.0
    vite-plugin-pages: ^0.33.1
    vite-plugin-windicss: ^1.9.4

  vue:
    '@vue/reactivity': ^3.5.17
    '@vueuse/core': ^13.5.0
    '@vueuse/math': ^13.5.0
    '@vueuse/nuxt': ^13.5.0
    floating-vue: ^5.2.2
    unplugin-vue-components: ^28.8.0
    unplugin-vue-markdown: ^28.3.1
    vue: ^3.5.17
    vue-eslint-parser: ^10.2.0
    vue-flow-layout: ^0.1.1
    vue-router: ^4.5.1
    vue-virtual-scroller: ^2.0.0-beta.8

autoInstallPeers: true
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
strictPeerDependencies: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - msw
  - nuxt-tsconfig-stub
  - sharp
  - simple-git-hooks
