packages:
  - bench
  - bench/fixtures/*
  - docs
  - playground
  - interactive
  - packages-engine/*
  - packages-integrations/*
  - packages-presets/*
  - virtual-shared/*
  - test/fixtures/*
  - examples/vue-cli4
  - examples/vue-cli5
catalog:
  '@ampproject/remapping': ^2.3.0
  '@antfu/eslint-config': ^3.15.0
  '@antfu/ni': ^23.2.0
  '@antfu/utils': ^8.1.0
  '@arethetypeswrong/cli': ^0.17.3
  '@babel/core': ^7.26.0
  '@babel/plugin-syntax-jsx': ^7.25.9
  '@babel/preset-typescript': ^7.26.0
  '@codemirror/lang-css': ^6.3.1
  '@codemirror/lang-html': ^6.4.9
  '@codemirror/lang-javascript': ^6.2.2
  '@codemirror/lang-xml': ^6.1.0
  '@csstools/normalize.css': ^12.1.1
  '@iconify-json/carbon': ^1.2.5
  '@iconify-json/iconoir': ^1.2.7
  '@iconify-json/la': ^1.2.1
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/tabler': ^1.2.14
  '@iconify-json/teenyicons': ^1.2.2
  '@iconify-json/twemoji': ^1.2.2
  '@iconify-json/uim': ^1.2.3
  '@iconify-json/vscode-icons': ^1.2.10
  '@iconify/json': ^2.2.298
  '@iconify/types': ^2.0.0
  '@iconify/utils': ^2.2.1
  '@nuxt/devtools': ^1.7.0
  '@nuxt/kit': ^3.15.2
  '@nuxt/schema': ^3.15.2
  '@shikijs/markdown-it': ^2.1.0
  '@shikijs/vitepress-twoslash': ^2.1.0
  '@sveltejs/kit': ^2.16.1
  '@types/connect': ^3.4.38
  '@types/css-tree': ^2.3.10
  '@types/fs-extra': ^11.0.4
  '@types/js-yaml': ^4.0.9
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/node': ^22.10.7
  '@types/prettier': ^2.7.3
  '@types/pug': ^2.0.10
  '@types/react': ^18.3.18
  '@types/webpack': ^5.28.5
  '@types/webpack-sources': ^3.2.3
  '@types/ws': ^8.5.13
  '@typescript-eslint/utils': ^8.21.0
  '@vitejs/plugin-legacy': ^6.0.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitest/ui': ^3.0.3
  '@vue/reactivity': ^3.5.13
  '@vueuse/core': ^12.4.0
  '@vueuse/math': ^12.4.0
  '@vueuse/nuxt': ^12.4.0
  astro: ^4.16.18
  autoprefixer: ^10.4.20
  brotli-size: ^4.0.0
  bumpp: ^9.10.1
  cac: ^6.7.14
  chokidar: ^3.6.0
  codemirror: ^6.0.1
  codemirror-theme-vars: ^0.1.2
  colorette: ^2.0.20
  consola: ^3.4.0
  core-js: ^3.40.0
  cross-env: ^7.0.3
  css-tree: ^3.1.0
  eslint: ^9.18.0
  eslint-plugin-antfu: ^2.7.0
  eslint-vitest-rule-tester: ^1.1.0
  esno: ^4.8.0
  execa: ^9.5.2
  find-up: ^6.3.0
  floating-vue: ^5.2.2
  fs-extra: ^11.3.0
  fuse.js: ^7.0.0
  fzf: ^0.5.2
  gzip-size: ^6.0.0
  jiti: ^2.4.2
  js-yaml: ^4.1.0
  jsdom: ^26.0.0
  knitwork: ^1.2.0
  lint-staged: ^15.4.1
  local-pkg: ^1.0.0
  lru-cache: ^10.4.3
  lz-string: ^1.5.0
  magic-string: ^0.30.17
  markdown-it-link-attributes: ^4.0.1
  msw: ^2.7.0
  npm-run-path: ^6.0.0
  nuxt: ^3.15.2
  nuxt-tsconfig-stub: ^0.0.2
  ofetch: ^1.4.1
  p-limit: ^6.2.0
  pathe: ^2.0.2
  perfect-debounce: ^1.0.0
  pnpm: ^9.15.4
  postcss: ^8.5.1
  postcss-nested: ^7.0.2
  prettier: ^2.8.8
  prettier-plugin-svelte: ^2.10.1
  pug: ^3.0.3
  react: ^18.3.1
  rimraf: ^6.0.1
  rollup: ^4.31.0
  sanitize.css: ^13.0.0
  semver: ^7.6.3
  shiki: ^2.1.0
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  sirv: ^3.0.0
  splitpanes: ^3.1.8
  std-env: ^3.8.0
  svelte: ^4.2.19
  svelte-eslint-parser: ^0.42.0
  synckit: ^0.9.2
  tailwindcss: ^3.4.17
  taze: ^18.2.0
  terser: ^5.37.0
  theme-vitesse: ^0.8.3
  tinyglobby: ^0.2.10
  tsup: ^8.3.5
  tsx: ^4.19.2
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unconfig: ~0.6.1
  unplugin: ^2.1.2
  unplugin-utils: ^0.2.3
  unplugin-auto-import: ^19.0.0
  unplugin-vue-components: ^28.0.0
  unplugin-vue-markdown: ^28.1.0
  vite: ^6.0.11
  vite-plugin-inspect: ^10.0.7
  vite-plugin-pages: ^0.32.4
  vite-plugin-windicss: ^1.9.4
  vitepress: ^1.6.1
  vitepress-plugin-group-icons: ^1.3.5
  vitest: ^3.0.3
  vue: ^3.5.13
  vue-eslint-parser: ^9.4.3
  vue-flow-layout: ^0.1.1
  vue-router: ^4.5.0
  vue-virtual-scroller: ^2.0.0-beta.8
  webpack: ^5.97.1
  webpack-sources: ^3.2.3
  windicss: ^3.5.6
