autoInstallPeers: true

catalogMode: prefer

cleanupUnusedCatalogs: true

ignoreWorkspaceRootCheck: true

shamefullyHoist: true

shellEmulator: true

packages:
  - bench
  - bench/fixtures/*
  - docs
  - playground
  - interactive
  - packages-engine/*
  - packages-integrations/*
  - packages-presets/*
  - packages-deprecated/*
  - virtual-shared/*
  - test/fixtures/*

overrides:
  is-arguments: npm:@nolyfill/is-arguments@^1.0.44
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  is-generator-function: npm:@nolyfill/is-generator-function@^1.0.44
  is-regex: npm:@nolyfill/is-regex@^1.0.44
  is-typed-array: npm:@nolyfill/is-typed-array@^1.0.44
  object.assign: npm:@nolyfill/object.assign@^1.0.44
  side-channel: npm:@nolyfill/side-channel@^1.0.44
  which-typed-array: npm:@nolyfill/which-typed-array@^1.0.44

catalogs:
  build:
    '@jridgewell/remapping': ^2.3.5
    brotli-size: ^4.0.0
    bumpp: ^11.0.1
    gzip-size: ^6.0.0
    rollup: ^4.60.1
    terser: ^5.46.1
    tsdown: ^0.21.7
    tsup: ^8.5.1
    webpack: ^5.105.4
    webpack-sources: ^3.3.4
  css:
    '@codemirror/lang-css': ^6.3.1
    '@csstools/normalize.css': ^12.1.1
    autoprefixer: ^10.4.27
    css-tree: ^3.2.1
    postcss: ^8.5.9
    postcss-nested: ^7.0.2
    sanitize.css: ^13.0.0
    windicss: ^3.5.6
  docs:
    '@codemirror/lang-html': ^6.4.11
    '@codemirror/lang-javascript': ^6.2.5
    '@codemirror/lang-xml': ^6.1.0
    '@oxc-parser/binding-wasm32-wasi': ^0.124.0
    '@shikijs/markdown-it': ^3.23.0
    '@shikijs/vitepress-twoslash': ^3.23.0
    codemirror: ^6.0.1
    codemirror-theme-vars: ^0.1.2
    markdown-it-link-attributes: ^4.0.1
    pug: ^3.0.4
    shiki: ^3.23.0
    theme-vitesse: ^1.0.0
    vitepress: ^2.0.0-alpha.17
    vitepress-plugin-group-icons: ^1.7.3
    vitepress-plugin-llms: ^1.12.0
  eslint:
    '@antfu/eslint-config': ^8.1.0
    eslint: ^10.2.0
    eslint-plugin-antfu: ^3.2.2
    eslint-plugin-format: ^2.0.1
    eslint-vitest-rule-tester: ^3.1.0
    svelte-eslint-parser: ^1.6.0
  frameworks:
    astro: ^5.18.1
    react: ^18.3.1
  icons:
    '@iconify-json/carbon': ^1.2.20
    '@iconify-json/iconoir': ^1.2.10
    '@iconify-json/la': ^1.2.1
    '@iconify-json/logos': ^1.2.11
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.10
    '@iconify-json/tabler': ^1.2.33
    '@iconify-json/teenyicons': ^1.2.2
    '@iconify-json/twemoji': ^1.2.5
    '@iconify-json/uim': ^1.2.3
    '@iconify-json/vscode-icons': ^1.2.45
    '@iconify/types': ^2.0.0
    '@iconify/utils': ^3.1.0
  nuxt:
    '@nuxt/kit': ^4.4.2
    nuxt: ^4.4.2
    nuxt-tsconfig-stub: ^0.0.2
    pkg-types: ^2.3.0
  oxc:
    oxc-parser: ^0.124.0
    oxc-walker: ^0.7.0
  svelte:
    prettier-plugin-svelte: ^2.10.1
    svelte: ^5.55.2
  testing:
    '@vitest/ui': ^4.1.3
    jsdom: ^29.0.2
    msw: ^2.7.0
    vitest: ^4.1.3
  types:
    '@types/connect': ^3.4.38
    '@types/css-tree': ^2.3.11
    '@types/fs-extra': ^11.0.4
    '@types/js-yaml': ^4.0.9
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^25.5.2
    '@types/prettier': ^2.7.3
    '@types/pug': ^2.0.10
    '@types/react': ^18.3.28
    '@types/splitpanes': ^2.2.6
    '@types/ws': ^8.18.1
    '@vitejs/devtools-kit': ^0.0.0-alpha.10
  typescript:
    '@typescript-eslint/utils': ^8.58.1
    '@typescript/native-preview': latest
    tsx: ^4.21.0
    typescript: 5.8.3
  utils:
    '@antfu/ni': ^30.0.0
    '@antfu/utils': ^9.3.0
    '@arethetypeswrong/cli': ^0.18.2
    acorn: ^8.16.0
    cac: ^7.0.0
    chokidar: ^5.0.0
    colorette: ^2.0.20
    consola: ^3.4.2
    execa: ^9.6.1
    fs-extra: ^11.3.4
    fuse.js: ^7.3.0
    fzf: ^0.5.2
    js-yaml: ^4.1.1
    knitwork: ^1.3.0
    lint-staged: ^16.4.0
    local-pkg: ^1.1.2
    lru-cache: ^11.3.2
    lz-string: ^1.5.0
    magic-string: ^0.30.21
    ofetch: ^1.5.1
    p-limit: ^7.3.0
    pathe: ^2.0.3
    perfect-debounce: ^2.1.0
    pnpm: ^10.33.0
    premove: ^4.0.0
    prettier: ^2.8.8
    publint: ^0.3.18
    semver: ^7.7.4
    simple-git: ^3.35.2
    simple-git-hooks: ^2.13.1
    sirv: ^3.0.2
    splitpanes: ^4.0.4
    std-env: ^4.0.0
    synckit: ^0.11.12
    taze: ^19.11.0
    tinyglobby: ^0.2.16
    unconfig: ^7.5.0
    unplugin: ^3.0.0
    unplugin-auto-import: ^21.0.0
    unplugin-utils: ^0.3.1
    zimmerframe: ^1.1.4
  vite:
    '@vitejs/plugin-legacy': ^8.0.1
    '@vitejs/plugin-vue': ^6.0.5
    vite: ^8.0.7
    vite-plugin-inspect: ^12.0.0-beta.1
    vite-plugin-pages: ^0.33.3
    vite-plugin-windicss: ^1.9.4
  vscode:
    vscode-ext-gen: ^1.6.0
    vscode-languageclient: ^9.0.1
    vscode-languageserver: ^9.0.1
    vscode-languageserver-textdocument: ^1.0.12
  vue:
    '@vue/reactivity': ^3.5.32
    '@vueuse/core': ^14.2.1
    '@vueuse/math': ^14.2.1
    '@vueuse/nuxt': ^14.2.1
    floating-vue: ^5.2.2
    unplugin-vue-components: ^32.0.0
    unplugin-vue-markdown: ^30.0.0
    vue: ^3.5.32
    vue-eslint-parser: ^10.4.0
    vue-flow-layout: ^0.2.0
    vue-router: ^5.0.4
    vue-virtual-scroller: ^2.0.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - msw
  - nuxt-tsconfig-stub
  - sharp
  - simple-git-hooks

strictPeerDependencies: false
