/**
 * Generated by tsnapi — public API snapshot of `@unocss/postcss/esm`
 */
// #region Functions
export declare function createPlugin(_: UnoPostcssPluginOptions): (_: Root, _: Result) => Promise<void>;
// #endregion

// #region Referenced (internal)
interface UnoPostcssPluginOptions {
  content?: (string | {
    raw: string;
    extension: string;
  })[];
  directiveMap?: {
    apply?: string;
    screen?: string;
    theme?: string;
    unocss?: string;
  };
  cwd?: string;
  configOrPath?: string | UserConfig;
}
// #endregion