/**
 * Generated by tsnapi — public API snapshot of `@unocss/postcss`
 */
// #region Interfaces
export interface UnoPostcssPluginOptions {
  content?: (string | {
    raw: string;
    extension: string;
  })[];
  directiveMap?: {
    apply?: string;
    screen?: string;
    theme?: string;
    unocss?: string;
  };
  cwd?: string;
  configOrPath?: string | UserConfig;
}
// #endregion

// #region Default Export
declare namespace _default {
  export var postcss: boolean;
  var _a: typeof unocss;
  export var default: typeof unocss;
}
export default _default
// #endregion