/**
 * Generated by tsnapi — public API snapshot of `@unocss/language-server`
 */
// #region Interfaces
export interface MatchedPosition {
  start: number;
  end: number;
  text: string;
}
export interface ServerSettings {
  languageIds: string[];
  root: string | string[] | undefined;
  include: string | string[] | undefined;
  exclude: string | string[] | undefined;
  underline: boolean;
  colorPreview: boolean;
  colorPreviewRadius: string;
  remToPxPreview: boolean;
  remToPxRatio: number;
  selectionStyle: boolean;
  strictAnnotationMatch: boolean;
  autocompleteMatchType: 'prefix' | 'fuzzy';
  autocompleteStrict: boolean;
  autocompleteMaxItems: number;
}
// #endregion

// #region Types
export type UnoContext = UnocssPluginContext<UserConfig<any>>;
// #endregion

// #region Classes
export declare class ContextManager {
  cwd: string;
  private connection;
  ready: Promise<void>;
  contextsMap: Map<string, UnoContext$1>;
  configSources: string[];
  private fileContextCache;
  private configExistsCache;
  private loadingContexts;
  private discoveredConfigs;
  private readonly defaultUnocssConfig;
  private readonly workspaceRoots;
  events: import("@unocss/core").Emitter<{
    reload: () => void;
    unload: (context: UnocssPluginContext<UserConfig<any>>) => void;
    contextLoaded: (context: UnocssPluginContext<UserConfig<any>>) => void;
    contextReload: (context: UnocssPluginContext<UserConfig<any>>) => void;
    contextUnload: (context: UnocssPluginContext<UserConfig<any>>) => void;
  }>;
  constructor(_: string, _: Connection, _?: string[]);
  private log;
  private warn;
  isTarget(_: string): boolean;
  get contexts(): UnocssPluginContext<UserConfig<any>>[];
  setRoots(_: string[]): Promise<void>;
  reload(): Promise<void>;
  unloadContext(_: string): Promise<void>;
  unload(_: string): Promise<void>;
  private clearFileContextCache;
  private resetCaches;
  private loadRoots;
  loadContextInDirectory(_: string): Promise<UnoContext$1>;
  private loadContext;
  private setupYarnPnp;
  private setupContextReload;
  private logConfigInfo;
  private finishLoading;
  resolveClosestContext(_: string, _: string): Promise<UnoContext$1 | undefined>;
  private discoverAndLoadConfig;
  private findConfigDirectory;
  private getWorkspaceBoundary;
  private hasConfigFiles;
  private cacheSearchPath;
}
// #endregion

// #region Functions
export declare function addRemToPxComment(_?: string, _?: number): string;
export declare function clearDocumentCache(_: string): void;
export declare function getColorString(_: string, _?: Map<string, string>): string | undefined;
export declare function getCSS(_: UnoGenerator, _: string | string[]): Promise<string>;
export declare function getCssVariables(_: string): Map<string, string>;
export declare function getMatchedPositionsFromCode(_: UnoGenerator, _: string, _?: string, _?: GetMatchedPositionsOptions): Promise<(readonly [start: number, end: number, text: string])[]>;
export declare function getMatchedPositionsFromDoc(_: UnoGenerator, _: string, _: string, _?: boolean, _?: boolean): any;
export declare function getPrettiedCSS(_: UnoGenerator, _: string | string[], _: number): Promise<{
  prettified: string;
  css: string;
  layers: string[];
  getLayer: (name?: string) => string | undefined;
  getLayers: (includes?: string[], excludes?: string[]) => string;
  setLayer: (layer: string, callback: (content: string) => Promise<string>) => Promise<string>;
  matched: Set<string>;
}>;
export declare function getPrettiedMarkdown(_: UnoGenerator, _: string | string[], _: number): Promise<string>;
export declare function isSubdir(_: string, _: string): boolean | "";
export declare function isVueWithPug(_: string, _: string): boolean;
export declare function parseColorToRGBA(_: string): Color | undefined;
export declare function shouldProvideAutocomplete(_: string, _: string, _: number): boolean;
// #endregion

// #region Variables
export declare const defaultSettings: ServerSettings;
// #endregion

// #region Referenced (internal)
declare namespace Color {
  function create(_: decimal, _: decimal, _: decimal, _: decimal): Color;
  function is(_: any): value is Color;
}
interface GetMatchedPositionsOptions {
  isPug?: boolean;
  includeRegex?: RegExp[];
  excludeRegex?: RegExp[];
}
type UnoContext$1 = UnocssPluginContext<UserConfig<any>> | null | undefined;
// #endregion