/**
 * Generated by tsnapi — public API snapshot of `@unocss/eslint-plugin`
 */
// #region Interfaces
export interface UnoCSSEslintConfigs {
  recommended: UnoCSSEslintRecommendedConfig;
  flat: UnoCSSEslintFlatConfig;
}
export interface UnoCSSEslintFlatConfig extends Linter.Config {
  plugins: {
    unocss: any;
  };
  rules: {
    readonly 'unocss/order': Linter.RuleEntry<UnocssOrder>;
    readonly 'unocss/order-attributify': Linter.RuleEntry<[]>;
    readonly 'unocss/blocklist'?: Linter.RuleEntry<[]>;
    readonly 'unocss/enforce-class-compile'?: Linter.RuleEntry<UnocssEnforceClassCompile>;
  };
}
export interface UnoCSSEslintPlugin {
  rules: Record<string, LooseRuleDefinition>;
}
export interface UnoCSSEslintPluginModule extends UnoCSSEslintPlugin {
  configs: UnoCSSEslintConfigs;
}
export interface UnoCSSEslintRecommendedConfig extends Linter.LegacyConfig {
  rules: {
    readonly '@unocss/order': Linter.RuleEntry<UnocssOrder>;
    readonly '@unocss/order-attributify': Linter.RuleEntry<[]>;
    readonly '@unocss/blocklist'?: Linter.RuleEntry<[]>;
    readonly '@unocss/enforce-class-compile'?: Linter.RuleEntry<UnocssEnforceClassCompile>;
  };
}
// #endregion

// #region Variables
export declare const configs: UnoCSSEslintConfigs;
// #endregion

// #region Default Export
declare const _default: UnoCSSEslintPluginModule;
export default _default
// #endregion

// #region Referenced (internal)
type UnocssEnforceClassCompile = [] | [{
  prefix?: string;
  enableFix?: boolean;
}];
type UnocssOrder = [] | [{
  unoFunctions?: string[];
  unoVariables?: string[];
}];
// #endregion