// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    FileIcon: typeof import('./components/FileIcon.vue')['default']
    ModuleId: typeof import('./components/ModuleId.vue')['default']
    ModuleInfo: typeof import('./components/ModuleInfo.vue')['default']
    ModuleTreeNode: typeof import('./components/ModuleTreeNode.vue')['default']
    NarBar: typeof import('./components/NarBar.vue')['default']
    Overview: typeof import('./components/Overview.vue')['default']
    ReplPlayground: typeof import('./components/ReplPlayground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    StatusBar: typeof import('./components/StatusBar.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}

export {}
