/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Analyzer: typeof import('./components/Analyzer.vue')['default']
    AnalyzerItem: typeof import('./components/AnalyzerItem.vue')['default']
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    Copy: typeof import('./components/Copy.vue')['default']
    FileIcon: typeof import('./components/FileIcon.vue')['default']
    ModuleId: typeof import('./components/ModuleId.vue')['default']
    ModuleInfo: typeof import('./components/ModuleInfo.vue')['default']
    ModuleTreeNode: typeof import('./components/ModuleTreeNode.vue')['default']
    NarBar: typeof import('./components/NarBar.vue')['default']
    Overview: typeof import('./components/Overview.vue')['default']
    OverviewTabs: typeof import('./components/OverviewTabs.vue')['default']
    ReplPlayground: typeof import('./components/ReplPlayground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    StatusBar: typeof import('./components/StatusBar.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}
