/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./components/foo/bar/tt.vue/a.vue')['default']
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    FileIcon: typeof import('./components/FileIcon.vue')['default']
    ModuleId: typeof import('./components/ModuleId.vue')['default']
    ModuleInfo: typeof import('./components/ModuleInfo.vue')['default']
    ModuleTreeNode: typeof import('./components/ModuleTreeNode.vue')['default']
    NarBar: typeof import('./components/NarBar.vue')['default']
    Overview: typeof import('./components/Overview.vue')['default']
    ReplPlayground: typeof import('./components/ReplPlayground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    StatusBar: typeof import('./components/StatusBar.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}
