/**
 * Generated by tsnapi — public API snapshot of `@unocss/svelte-scoped/preprocess`
 */
// #region Interfaces
export interface TransformApplyOptions {
  applyVariables?: string | string[] | false;
}
export interface TransformClassesOptions {
  classPrefix?: string;
  combine?: boolean;
  hashFn?: (_: string) => string;
  hashSafelistClasses?: boolean;
}
export interface TransformDirectivesOptions {
  transformThemeDirective?: boolean;
}
export interface UnocssSveltePreprocessOptions extends TransformClassesOptions, TransformApplyOptions, TransformDirectivesOptions {
  configOrPath?: UserConfig | string;
}
// #endregion

// #region Default Export
declare function _default(_?: UnocssSveltePreprocessOptions, _?: Pick<UnocssPluginContext, 'ready' | 'uno'>, _?: () => boolean): PreprocessorGroup;
export default _default
// #endregion