/**
 * Generated by tsnapi — public API snapshot of `@unocss/svelte-scoped/vite`
 */
// #region Default Export
declare function _default(_?: UnocssSvelteScopedViteOptions): Plugin[];
export default _default
// #endregion

// #region Referenced (internal)
interface UnocssSvelteScopedViteOptions extends UnocssSveltePreprocessOptions {
  classPrefix?: string;
  injectReset?: string;
  onlyGlobal?: boolean;
  cssFileTransformers?: PluginOptions['transformers'];
}
// #endregion