/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-legacy-compat`
 */
// #region Interfaces
export interface LegacyCompatOptions {
  commaStyleColorFunction?: boolean;
  legacyColorSpace?: boolean;
}
// #endregion

// #region Variables
export declare const presetLegacyCompat: import("@unocss/core").PresetFactory<object, LegacyCompatOptions>;
// #endregion

// #region Default Export
declare const _default: import("@unocss/core").PresetFactory<object, LegacyCompatOptions>;
export default _default
// #endregion