/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-wind3`
 */
// #region Interfaces
export interface PresetWind3Options extends PresetMiniOptions {
  important?: boolean | string;
}
// #endregion

// #region Functions
export declare function variants(_: PresetWind3Options): Variant<Theme$1>[];
// #endregion

// #region Variables
export declare const presetWind: import("@unocss/core").PresetFactory<import("@unocss/preset-mini").Theme, PresetWind3Options>;
export declare const presetWind3: import("@unocss/core").PresetFactory<import("@unocss/preset-mini").Theme, PresetWind3Options>;
export declare const rules: Rule<Theme>[];
export declare const shortcuts: import("@unocss/core").Shortcut<import("@unocss/preset-mini").Theme>[];
export declare const theme: Theme;
// #endregion

// #region Default Export
declare const _default: import("@unocss/core").PresetFactory<import("@unocss/preset-mini").Theme, PresetWind3Options>;
export default _default
// #endregion

// #region Other
export { colors }
export { preflights }
export { Theme }
// #endregion