/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-wind3/rules`
 */
// #region Variables
export declare const accents: Rule[];
export declare const animations: Rule<Theme>[];
export declare const backdropFilterBase: {
  '--un-backdrop-blur': string;
  '--un-backdrop-brightness': string;
  '--un-backdrop-contrast': string;
  '--un-backdrop-grayscale': string;
  '--un-backdrop-hue-rotate': string;
  '--un-backdrop-invert': string;
  '--un-backdrop-opacity': string;
  '--un-backdrop-saturate': string;
  '--un-backdrop-sepia': string;
};
export declare const backgroundBlendModes: Rule[];
export declare const backgroundStyles: Rule[];
export declare const borderSpacingBase: {
  '--un-border-spacing-x': number;
  '--un-border-spacing-y': number;
};
export declare const carets: Rule[];
export declare const columns: Rule<Theme>[];
export declare const container: Rule<Theme>[];
export declare const containerShortcuts: Shortcut<Theme>[];
export declare const cssVariables: Rule[];
export declare const divides: Rule[];
export declare const dynamicViewportHeight: Rule[];
export declare const filterBase: {
  '--un-blur': string;
  '--un-brightness': string;
  '--un-contrast': string;
  '--un-drop-shadow': string;
  '--un-grayscale': string;
  '--un-hue-rotate': string;
  '--un-invert': string;
  '--un-saturate': string;
  '--un-sepia': string;
};
export declare const filters: Rule<Theme>[];
export declare const fontVariantNumeric: Rule[];
export declare const fontVariantNumericBase: {
  '--un-ordinal': string;
  '--un-slashed-zero': string;
  '--un-numeric-figure': string;
  '--un-numeric-spacing': string;
  '--un-numeric-fraction': string;
};
export declare const hyphens: Rule[];
export declare const imageRenderings: Rule[];
export declare const isolations: Rule[];
export declare const lineClamps: Rule[];
export declare const listStyle: Rule[];
export declare const mixBlendModes: Rule[];
export declare const objectPositions: Rule[];
export declare const overscrolls: Rule[];
export declare const placeholders: Rule[];
export declare const rules: Rule<Theme>[];
export declare const screenReadersAccess: Rule[];
export declare const scrollBehaviors: Rule[];
export declare const scrolls: Rule[];
export declare const scrollSnapTypeBase: {
  '--un-scroll-snap-strictness': string;
};
export declare const spaces: Rule[];
export declare const tables: Rule<Theme>[];
export declare const textTransforms: Rule[];
export declare const touchActionBase: {
  '--un-pan-x': string;
  '--un-pan-y': string;
  '--un-pinch-zoom': string;
};
export declare const touchActions: Rule[];
export declare const viewTransition: Rule[];
export declare const writingModes: Rule[];
export declare const writingOrientations: Rule[];
// #endregion