/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-wind3/shortcuts`
 */
// #region Variables
export declare const shortcuts: import("@unocss/core").Shortcut<import("@unocss/preset-mini").Theme>[];
// #endregion