/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-wind3/variants`
 */
// #region Functions
export declare function variantColorMix<Theme extends object>(): VariantObject<Theme>;
export declare function variants(_: PresetWind3Options): Variant<Theme$1>[];
// #endregion

// #region Variables
export declare const placeholderModifier: VariantFunction;
export declare const variantColorsScheme: Variant[];
export declare const variantCombinators: Variant[];
export declare const variantContrasts: Variant[];
export declare const variantMotions: Variant[];
export declare const variantOrientations: Variant[];
export declare const variantSpaceAndDivide: Variant;
export declare const variantStickyHover: Variant[];
// #endregion