export type UtilityNames =
  | 'align'
  | 'animate'
  | 'backdrop'
  | 'bg'
  | 'blend'
  | 'border'
  | 'box'
  | 'container'
  | 'content'
  | 'cursor'
  | 'display'
  | 'divide'
  | 'filter'
  | 'flex'
  | 'font'
  | 'gap'
  | 'gradient'
  | 'grid'
  | 'h'
  | 'icon'
  | 'justify'
  | 'list'
  | 'm'
  | 'opacity'
  | 'order'
  | 'outline'
  | 'overflow'
  | 'p'
  | 'place'
  | 'pos'
  | 'ring'
  | 'select'
  | 'shadow'
  | 'space'
  | 'table'
  | 'text'
  | 'transform'
  | 'transition'
  | 'underline'
  | 'w'
  | 'z'

export type VariantNames =
  | 'active'
  | 'after'
  | 'all'
  | 'before'
  | 'child'
  | 'dark'
  | 'enabled'
  | 'first'
  | 'focus'
  | 'hover'
  | 'last'
  | 'lg'
  | 'light'
  | 'md'
  | 'root'
  | 'sm'
  | 'xl'
  | 'xxl'

export type AttributifyNames<Prefix extends string = ''> =
  | `${Prefix}${UtilityNames}`
  | `${Prefix}${VariantNames}`
  | `${Prefix}${VariantNames}:${UtilityNames}`

export interface AttributifyAttributes extends Partial<Record<AttributifyNames, string>> {}
