/**
 * Generated by tsnapi — public API snapshot of `@unocss/rollup`
 */
// #region Interfaces
export interface RollupPluginConfig<Theme extends object = object> extends UserConfig<Theme> {
  checkImport?: boolean;
}
// #endregion

// #region Types
export type UnoCSSRollupPlugin = Plugin;
// #endregion

// #region Functions
export declare function defineConfig<Theme extends object>(_: RollupPluginConfig<Theme>): RollupPluginConfig<Theme>;
// #endregion

// #region Default Export
export default function RollupPlugin<Theme extends object>(_?: RollupPluginConfig<Theme> | string, _?: UserConfigDefaults): UnoCSSRollupPlugin;
// #endregion