/**
 * Generated by tsnapi — public API snapshot of `@unocss/rule-utils`
 */
// #region Interfaces
export interface BreakpointsContext {
  theme: object;
  generator?: {
    userConfig?: {
      theme?: object;
    };
  };
}
export interface CSSColorValue {
  type: string;
  components: (string | number)[];
  alpha: string | number | undefined;
}
export interface ParsedColorValue {
  color?: string;
  opacity: string;
  name: string;
  no: string;
  cssColor: CSSColorValue | undefined;
  alpha: string | number | undefined;
}
export interface PseudoVariantOptions {
  attributifyPseudo?: boolean;
  prefix?: string | string[];
}
export interface PseudoVariantUtilities<Theme extends object = object> {
  getBracket: typeof getBracket;
  h: {
    bracket: (_: string, _?: Theme) => string | undefined;
  };
  variantGetBracket: typeof variantGetBracket;
}
// #endregion

// #region Types
export type BreakpointsThemeKey = 'breakpoint' | 'breakpoints' | 'verticalBreakpoint' | 'verticalBreakpoints';
export type RGBAColorValue = [number, number, number, number] | [number, number, number];
export type ValueHandler<K extends string, T extends object> = { [S in K]: ValueHandler<K, T>; } & {
  (_: string, _?: T): string | undefined;
  __options: {
    sequence: K[];
  };
};
export type ValueHandlerCallback<T extends object> = (_: string, _?: T) => string | number | undefined;
// #endregion

// #region Functions
export declare function calcMaxWidthBySize(_: string): string;
export declare function colorOpacityToString(_: CSSColorValue): string | number;
export declare function colorToString(_: CSSColorValue | string, _?: string | number): string;
export declare function createPartClasses<T extends object = object>(): VariantObject<T>;
export declare function createPseudoClassesAndElements<T extends object = object>(_: PseudoVariantUtilities): VariantObject<T>[];
export declare function createPseudoClassFunctions<T extends object = object>(_: PseudoVariantUtilities): VariantObject<T>;
export declare function createTaggedPseudoClasses<T extends object = object>(_: PseudoVariantOptions, _: PseudoVariantUtilities): VariantObject<T>[];
export declare function createTaggedPseudoClassMatcher<T extends object = object>(_: string, _: string, _: string, _: PseudoVariantUtilities): VariantObject<T>;
export declare function createValueHandler<K extends string, T extends object>(_: Record<K, ValueHandlerCallback<T>>): ValueHandler<K, T>;
export declare function generateBreakpointMediaQuery(_: string, _?: 'lt' | 'at', _?: string): string;
export declare function getBracket(_: string, _: string, _: string): string[] | undefined;
export declare function getStringComponent(_: string, _: string, _: string, _: string | string[]): string[] | undefined;
export declare function getStringComponents(_: string, _: string | string[], _?: number, _?: string, _?: string): string[] | undefined;
export declare function hasIconFn(_: string): boolean;
export declare function hasThemeFn(_: string): boolean;
export declare function hex2rgba(_?: string): RGBAColorValue | undefined;
export declare function isInterpolatedMethod(_?: string): boolean;
export declare function parseCssColor(_?: string): CSSColorValue | undefined;
export declare function resolveBreakpoints({ theme, generator }: BreakpointsContext, _?: BreakpointsThemeKey): {
  point: string;
  size: string;
}[] | undefined;
export declare function resolveScreenMediaQuery(_: object, _: string): string;
export declare function resolveVerticalBreakpoints(_: BreakpointsContext): {
  point: string;
  size: string;
}[] | undefined;
export declare function transformThemeFn(_: string, _: Record<string, any>, _?: boolean): string;
export declare function transformThemeString(_: string, _: Record<string, any>, _?: boolean): string | undefined;
export declare function variantBreakpoints(_?: 'breakpoint' | 'breakpoints'): VariantObject;
export declare function variantGetBracket(_: string, _: string, _: string[]): string[] | undefined;
export declare function variantGetParameter(_: Arrayable<string>, _: string, _: string[]): string[] | undefined;
export declare function variantMatcher<T extends object = object>(_: string, _: Arrayable<(input: VariantHandlerContext) => Record<string, any>>, _?: Omit<VariantObject<T>, 'match'>): VariantObject<T>;
export declare function variantParentMatcher<T extends object = object>(_: string, _: string): VariantObject<T>;
// #endregion

// #region Variables
export declare const alphaPlaceholders: string[];
export declare const alphaPlaceholdersRE: RegExp;
export declare const cssColorFunctions: string[];
export declare const excludedPseudo: string[];
export declare const hueInterpolationMethods: string[];
export declare const iconFnRE: RegExp;
export declare const polarColorSpace: string[];
export declare const PseudoClasses: Record<string, string>;
export declare const PseudoClassesAndElementsColonStr: string;
export declare const PseudoClassesAndElementsStr: string;
export declare const PseudoClassesColon: Record<string, string>;
export declare const PseudoClassesColonKeys: string[];
export declare const PseudoClassesColonStr: string;
export declare const PseudoClassesKeys: string[];
export declare const PseudoClassesMulti: Record<string, string[]>;
export declare const PseudoClassesMultiStr: string;
export declare const PseudoClassesStr: string;
export declare const PseudoClassFunctions: string[];
export declare const PseudoClassFunctionsStr: string;
export declare const rectangularColorSpace: string[];
export declare const themeFnRE: RegExp;
// #endregion