/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Analyzer: typeof import('./../../packages-integrations/inspector/client/components/Analyzer.vue')['default']
    AnalyzerItem: typeof import('./../../packages-integrations/inspector/client/components/AnalyzerItem.vue')['default']
    CodeMirror: typeof import('./../../packages-integrations/inspector/client/components/CodeMirror.vue')['default']
    Copy: typeof import('./../../packages-integrations/inspector/client/components/Copy.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    FileIcon: typeof import('./../../packages-integrations/inspector/client/components/FileIcon.vue')['default']
    HeaderBar: typeof import('./components/HeaderBar.vue')['default']
    ModuleId: typeof import('./../../packages-integrations/inspector/client/components/ModuleId.vue')['default']
    ModuleInfo: typeof import('./../../packages-integrations/inspector/client/components/ModuleInfo.vue')['default']
    ModuleTreeNode: typeof import('./../../packages-integrations/inspector/client/components/ModuleTreeNode.vue')['default']
    NarBar: typeof import('./../../packages-integrations/inspector/client/components/NarBar.vue')['default']
    Overview: typeof import('./../../packages-integrations/inspector/client/components/Overview.vue')['default']
    OverviewTabs: typeof import('./../../packages-integrations/inspector/client/components/OverviewTabs.vue')['default']
    PanelConfig: typeof import('./components/panel/PanelConfig.vue')['default']
    PanelCustomCss: typeof import('./components/panel/PanelCustomCss.vue')['default']
    PanelHtml: typeof import('./components/panel/PanelHtml.vue')['default']
    PanelOutputCss: typeof import('./components/panel/PanelOutputCss.vue')['default']
    Playground: typeof import('./components/Playground.vue')['default']
    Preview: typeof import('./components/Preview.vue')['default']
    ReplPlayground: typeof import('./../../packages-integrations/inspector/client/components/ReplPlayground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLayers: typeof import('./components/SelectLayers.vue')['default']
    SelectVersion: typeof import('./components/SelectVersion.vue')['default']
    Sidebar: typeof import('./../../packages-integrations/inspector/client/components/Sidebar.vue')['default']
    StatusBar: typeof import('./../../packages-integrations/inspector/client/components/StatusBar.vue')['default']
    Tabs: typeof import('./../../packages-integrations/inspector/client/components/Tabs.vue')['default']
    TitleBar: typeof import('./../../packages-integrations/inspector/client/components/TitleBar.vue')['default']
  }
}
