/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./../../packages/inspector/client/components/CodeMirror.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    FileIcon: typeof import('./../../packages/inspector/client/components/FileIcon.vue')['default']
    HeaderBar: typeof import('./components/HeaderBar.vue')['default']
    ModuleId: typeof import('./../../packages/inspector/client/components/ModuleId.vue')['default']
    ModuleInfo: typeof import('./../../packages/inspector/client/components/ModuleInfo.vue')['default']
    ModuleTreeNode: typeof import('./../../packages/inspector/client/components/ModuleTreeNode.vue')['default']
    NarBar: typeof import('./../../packages/inspector/client/components/NarBar.vue')['default']
    Overview: typeof import('./../../packages/inspector/client/components/Overview.vue')['default']
    PanelConfig: typeof import('./components/panel/PanelConfig.vue')['default']
    PanelHtml: typeof import('./components/panel/PanelHtml.vue')['default']
    PanelOutputCss: typeof import('./components/panel/PanelOutputCss.vue')['default']
    Playground: typeof import('./components/Playground.vue')['default']
    Preview: typeof import('./components/Preview.vue')['default']
    ReplPlayground: typeof import('./../../packages/inspector/client/components/ReplPlayground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../../packages/inspector/client/components/Sidebar.vue')['default']
    StatusBar: typeof import('./../../packages/inspector/client/components/StatusBar.vue')['default']
    TitleBar: typeof import('./../../packages/inspector/client/components/TitleBar.vue')['default']
  }
}
