/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-wind4`
 */
// #region Interfaces
export interface DarkModeSelectors {
  light?: string;
  dark?: string;
}
export interface PreflightsTheme {
  mode?: boolean | 'on-demand';
  process?: Arrayable<(entry: CSSEntry, ctx: PreflightContext<Theme>) => void>;
}
export interface PresetWind4Options extends PresetOptions {
  dark?: 'class' | 'media' | DarkModeSelectors;
  attributifyPseudo?: boolean;
  variablePrefix?: string;
  prefix?: string | string[];
  arbitraryVariants?: boolean;
  important?: boolean | string;
  preflights?: {
    reset?: boolean;
    theme?: PreflightsTheme['mode'] | PreflightsTheme;
    property?: boolean | {
      parent?: string | false;
      selector?: string;
    };
  };
}
export interface Theme {
  font?: Record<string, string>;
  colors?: Colors;
  spacing?: Record<string, string>;
  breakpoint?: Record<string, string>;
  verticalBreakpoint?: Record<string, string>;
  container?: Record<string, string>;
  text?: Record<string, {
    fontSize?: string;
    lineHeight?: string;
    letterSpacing?: string;
  }>;
  fontWeight?: Record<string, string>;
  tracking?: Record<string, string>;
  leading?: Record<string, string>;
  radius?: Record<string, string>;
  shadow?: Record<string, string | string[]>;
  insetShadow?: Record<string, string | string[]>;
  dropShadow?: Record<string, string | string[]>;
  textShadow?: Record<string, string | string[]>;
  ease?: Record<string, string>;
  blur?: Record<string, string>;
  perspective?: Record<string, string>;
  textStrokeWidth?: Record<string, string>;
  property?: Record<string, string>;
  default?: Record<string, Record<string, string>>;
  animation?: ThemeAnimation;
  duration?: Record<string, string>;
  containers?: {
    center?: boolean;
    padding?: string | Record<string, string>;
    maxWidth?: Record<string, string>;
  };
  aria?: Record<string, string>;
  data?: Record<string, string>;
  media?: Record<string, string>;
  supports?: Record<string, string>;
}
// #endregion

// #region Functions
export declare function postprocessors(_: PresetWind4Options): Postprocessor[];
export declare function variants(_: PresetWind4Options): Variant<Theme>[];
// #endregion

// #region Variables
export declare const preflights: (options: PresetWind4Options) => Preflight<Theme>[];
export declare const presetWind4: import("@unocss/core").PresetFactory<Theme, PresetWind4Options>;
export declare const rules: Rule<Theme$1>[];
export declare const shortcuts: import("@unocss/core").Shortcut<Theme>[];
export declare const shorthands: {
  position: string[];
  globalKeyword: string[];
};
export declare const theme: { /* collapsed */ }
// #endregion

// #region Default Export
declare const _default: import("@unocss/core").PresetFactory<Theme, PresetWind4Options>;
export default _default
// #endregion