/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-wind4/postprocess`
 */
// #region Functions
export declare function important({ important: option }: PresetWind4Options): Postprocessor[];
export declare function postprocessors(_: PresetWind4Options): Postprocessor[];
export declare function varPrefix({ variablePrefix: prefix }: PresetWind4Options): Postprocessor[];
// #endregion