/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-wind4/theme`
 */
// #region Interfaces
export interface Colors {
  [key: string]: Colors & {
    DEFAULT?: string;
  } | string;
}
export interface Theme {
  font?: Record<string, string>;
  colors?: Colors;
  spacing?: Record<string, string>;
  breakpoint?: Record<string, string>;
  verticalBreakpoint?: Record<string, string>;
  container?: Record<string, string>;
  text?: Record<string, {
    fontSize?: string;
    lineHeight?: string;
    letterSpacing?: string;
  }>;
  fontWeight?: Record<string, string>;
  tracking?: Record<string, string>;
  leading?: Record<string, string>;
  radius?: Record<string, string>;
  shadow?: Record<string, string | string[]>;
  insetShadow?: Record<string, string | string[]>;
  dropShadow?: Record<string, string | string[]>;
  textShadow?: Record<string, string | string[]>;
  ease?: Record<string, string>;
  blur?: Record<string, string>;
  perspective?: Record<string, string>;
  textStrokeWidth?: Record<string, string>;
  property?: Record<string, string>;
  default?: Record<string, Record<string, string>>;
  animation?: ThemeAnimation;
  duration?: Record<string, string>;
  containers?: {
    center?: boolean;
    padding?: string | Record<string, string>;
    maxWidth?: Record<string, string>;
  };
  aria?: Record<string, string>;
  data?: Record<string, string>;
  media?: Record<string, string>;
  supports?: Record<string, string>;
}
export interface ThemeAnimation {
  keyframes?: Record<string, string>;
  durations?: Record<string, string>;
  timingFns?: Record<string, string>;
  properties?: Record<string, object>;
  counts?: Record<string, string | number>;
  category?: Record<string, string>;
}
// #endregion

// #region Variables
export declare const animation: { /* collapsed */ }
export declare const aria: {
  busy: string;
  checked: string;
  disabled: string;
  expanded: string;
  hidden: string;
  pressed: string;
  readonly: string;
  required: string;
  selected: string;
};
export declare const blur: {
  DEFAULT: string;
  xs: string;
  sm: string;
  md: string;
  lg: string;
  xl: string;
  '2xl': string;
  '3xl': string;
};
export declare const breakpoint: {
  sm: string;
  md: string;
  lg: string;
  xl: string;
  '2xl': string;
};
export declare const colors: { /* collapsed */ }
export declare const container: { /* collapsed */ }
export declare const defaults: { /* collapsed */ }
export declare const dropShadow: {
  DEFAULT: string[];
  xs: string;
  sm: string;
  md: string;
  lg: string;
  xl: string;
  '2xl': string;
};
export declare const ease: {
  linear: string;
  in: string;
  out: string;
  'in-out': string;
  DEFAULT: string;
};
export declare const font: {
  sans: string;
  serif: string;
  mono: string;
};
export declare const fontWeight: {
  thin: string;
  extralight: string;
  light: string;
  normal: string;
  medium: string;
  semibold: string;
  bold: string;
  extrabold: string;
  black: string;
};
export declare const insetShadow: {
  '2xs': string;
  xs: string;
  sm: string;
  none: string;
};
export declare const leading: {
  none: string;
  tight: string;
  snug: string;
  normal: string;
  relaxed: string;
  loose: string;
};
export declare const media: { /* collapsed */ }
export declare const perspective: {
  dramatic: string;
  near: string;
  normal: string;
  midrange: string;
  distant: string;
};
export declare const property: {
  none: string;
  all: string;
  colors: string;
  opacity: string;
  shadow: string;
  transform: string;
  readonly DEFAULT: string;
};
export declare const radius: {
  DEFAULT: string;
  none: string;
  xs: string;
  sm: string;
  md: string;
  lg: string;
  xl: string;
  '2xl': string;
  '3xl': string;
  '4xl': string;
};
export declare const shadow: {
  DEFAULT: string[];
  '2xs': string;
  xs: string;
  sm: string[];
  md: string[];
  lg: string[];
  xl: string[];
  '2xl': string;
  none: string;
  inner: string;
};
export declare const spacing: { /* collapsed */ }
export declare const supports: {
  grid: string;
};
export declare const text: { /* collapsed */ }
export declare const textShadow: {
  none: string;
  '2xs': string;
  xs: string;
  sm: string[];
  md: string[];
  lg: string[];
};
export declare const textStrokeWidth: Theme['textStrokeWidth'];
export declare const theme: { /* collapsed */ }
export declare const tracking: {
  tighter: string;
  tight: string;
  normal: string;
  wide: string;
  wider: string;
  widest: string;
};
export declare const verticalBreakpoint: {
  sm: string;
  md: string;
  lg: string;
  xl: string;
  '2xl': string;
};
// #endregion