/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-wind4/utils`
 */
// #region Namespaces
export declare namespace valueHandlers {
  export function auto(_: string): "auto" | undefined;
  export function bracket(_: string, _?: Theme): string | undefined;
  export function bracketOfColor(_: string, _?: Theme): string | undefined;
  export function bracketOfFamily(_: string, _?: Theme): string | undefined;
  export function bracketOfLength(_: string, _?: Theme): string | undefined;
  export function bracketOfNumber(_: string, _?: Theme): string | undefined;
  export function bracketOfPosition(_: string, _?: Theme): string | undefined;
  export function cssvar(_: string): string | undefined;
  export function degree(_: string): string | undefined;
  export function fraction(_: string): string | undefined;
  export function global(_: string): string | undefined;
  export function none(_: string): "none" | undefined;
  export function number(_: string): number | undefined;
  export function numberWithUnit(_: string): string | undefined;
  export function percent(_: string): string | undefined;
  export function position(_: string): string | undefined;
  export function properties(_: string): string | undefined;
  export function px(_: string): string | undefined;
  export function rem(_: string): string | undefined;
  export function time(_: string): string | undefined;
}
// #endregion

// #region Functions
export declare function camelize(_: string): string;
export declare function colorableShadows(_: string | string[], _: string, _?: string): string[];
export declare function colorCSSGenerator(_: ReturnType<typeof parseColor>, _: string, _: string, _?: RuleContext<Theme>): [CSSObject, ...CSSValueInput[]] | undefined;
export declare function colorResolver(_: string, _: string): ([, body]: string[], _: RuleContext<Theme>) => (CSSValueInput | string)[] | undefined;
export declare function compressCSS(_: string, _?: boolean): string;
export declare function createRemToPxProcessor(_?: number): (_: UtilObject | CSSEntry) => void;
export declare function defineProperty(_: string, _?: {
  syntax?: string;
  inherits?: boolean;
  initialValue?: unknown;
}): CSSValueInput;
export declare function detectThemeValue(_: string, _: Theme): void;
export declare function directionSize(_: string, _?: Record<string, string[]>, _?: (_: string, _: string) => string): DynamicMatcher<Theme>;
export declare function generateThemeVariable(_: string, _: Arrayable<string>): string;
export declare function getThemeByKey(_: Theme, _: keyof Theme, _: string[]): any;
export declare function hasParseableColor(_: string | undefined, _: Theme): boolean;
export declare function hyphenate(_: string): string;
export declare function isSize(_: string): boolean;
export declare function makeGlobalStaticRules(_: string, _?: string): StaticRule[];
export declare function numberResolver(_: string, _?: string | number): number | undefined;
export declare function parseColor(_: string, _: Theme): {
  opacity: string | undefined;
  modifier: string | undefined;
  name: string;
  no: string | undefined;
  color: string;
  alpha: string | undefined;
  keys: string[] | undefined;
  readonly cssColor: import("@unocss/rule-utils").CSSColorValue | undefined;
} | undefined;
export declare function parseThemeColor(_: Theme, _: string[]): {
  color: string;
  no: string | undefined;
  keys: string[] | undefined;
} | undefined;
export declare function propertyTracking(_: string, _: string): void;
export declare function resolveBreakpoints({ theme, generator }: Readonly<VariantContext<Theme>>, _?: 'breakpoint' | 'verticalBreakpoint'): {
  point: string;
  size: string;
}[] | undefined;
export declare function resolveVerticalBreakpoints(_: Readonly<VariantContext<Theme>>): {
  point: string;
  size: string;
}[] | undefined;
export declare function splitShorthand(_: string, _: string): string[] | undefined;
export declare function themeTracking(_: string, _?: Arrayable<string>): void;
// #endregion

// #region Variables
export declare const CONTROL_NO_NEGATIVE: string;
export declare const cornerMap: Record<string, string[]>;
export declare const cssMathFnRE: RegExp;
export declare const cssVarFnRE: RegExp;
export declare const directionMap: Record<string, string[]>;
export declare const globalKeywords: string[];
export declare const h: import("@unocss/rule-utils").ValueHandler<string, Theme>;
export declare const handler: import("@unocss/rule-utils").ValueHandler<string, Theme>;
export declare const insetMap: Record<string, string[]>;
export declare const positionMap: Record<string, string>;
export declare const PRESET_NAME: string;
export declare const SpecialColorKey: {
  transparent: string;
  current: string;
  inherit: string;
};
export declare const trackedProperties: Map<string, string>;
export declare const trackedTheme: Set<string>;
export declare const xyzArray: string[];
export declare const xyzMap: Record<string, string[]>;
// #endregion

// #region Re-exports
export * from "@unocss/rule-utils";
// #endregion