/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-wind4/variants`
 */
// #region Functions
export declare function variantBreakpoints(): VariantObject<Theme>;
export declare function variantColorsMediaOrClass(_?: PresetWind4Options): Variant<Theme>[];
export declare function variantImportant(): VariantObject<Theme>;
export declare function variantPseudoClassesAndElements(): VariantObject<Theme>[];
export declare function variantPseudoClassFunctions(): VariantObject<Theme>;
export declare function variants(_: PresetWind4Options): Variant<Theme>[];
export declare function variantTaggedPseudoClasses(_?: PresetWind4Options): VariantObject<Theme>[];
// #endregion

// #region Variables
export declare const placeholderModifier: VariantFunction<Theme>;
export declare const variantAria: VariantObject<Theme>;
export declare const variantChildren: Variant<Theme>[];
export declare const variantColorsScheme: Variant<Theme>[];
export declare const variantCombinators: Variant<Theme>[];
export declare const variantContainerQuery: VariantObject<Theme>;
export declare const variantContrasts: Variant<Theme>[];
export declare const variantCssLayer: Variant<Theme>;
export declare const variantCustomMedia: VariantObject<Theme>;
export declare const variantDataAttribute: VariantObject<Theme>;
export declare const variantForcedColors: Variant<Theme>[];
export declare const variantImplicitGroup: Variant<Theme>;
export declare const variantInternalLayer: Variant<Theme>;
export declare const variantLanguageDirections: Variant<Theme>[];
export declare const variantMotions: Variant<Theme>[];
export declare const variantNegative: Variant<Theme>;
export declare const variantNoscript: VariantObject;
export declare const variantOrientations: Variant<Theme>[];
export declare const variantPartClasses: VariantObject<Theme>;
export declare const variantPrint: VariantObject<Theme>;
export declare const variantScope: Variant<Theme>;
export declare const variantScripting: VariantObject<Theme>;
export declare const variantSelector: Variant<Theme>;
export declare const variantStartingStyle: Variant<Theme>;
export declare const variantStickyHover: Variant<Theme>[];
export declare const variantSupports: VariantObject<Theme>;
export declare const variantSvgCombinators: Variant<Theme>[];
export declare const variantTaggedAriaAttributes: Variant<Theme>[];
export declare const variantTaggedDataAttributes: Variant<Theme>[];
export declare const variantTheme: Variant<Theme>;
export declare const variantVariables: Variant<Theme>;
// #endregion