/**
 * Generated by tsnapi — public API snapshot of `@unocss/transformer-variant-group`
 */
// #region Interfaces
export interface TransformerVariantGroupOptions {
  separators?: (':' | '-')[];
}
// #endregion

// #region Default Export
declare function _default(_?: TransformerVariantGroupOptions): SourceCodeTransformer;
export default _default
// #endregion