/**
 * Generated by tsnapi — public API snapshot of `@unocss/transformer-variant-group`
 */
// #region Interfaces
export interface TransformerVariantGroupOptions {
  separators?: (':' | '-')[];
}
// #endregion

// #region Default Export
export default function transformerVariantGroup(_?: TransformerVariantGroupOptions): SourceCodeTransformer;
// #endregion