/**
 * Generated by tsnapi — public API snapshot of `@unocss/nuxt`
 */
// #region Interfaces
export interface UnocssNuxtOptions extends UserConfig {
  mode?: VitePluginConfig['mode'];
  autoImport?: boolean;
  preflight?: boolean;
  disableNuxtInlineStyle?: boolean;
  nuxtLayers?: boolean;
  injectPosition?: 'first' | 'last' | number | {
    after?: string;
  };
  components?: boolean;
  attributify?: boolean | AttributifyOptions;
  tagify?: boolean | TagifyOptions;
  icons?: boolean | IconsOptions;
  webFonts?: boolean | WebFontsOptions;
  typography?: boolean | TypographyOptions;
  wind3?: boolean | PresetWind3Options;
  wind4?: boolean | PresetWind4Options;
}
// #endregion

// #region Default Export
declare const _default: import("@nuxt/schema").NuxtModule<UnocssNuxtOptions, UnocssNuxtOptions, false>;
export default _default
// #endregion