/**
 * Generated by tsnapi — public API snapshot of `@unocss/extractor-arbitrary-variants`
 */
// #region Functions
export declare function extractorArbitraryVariants(): Extractor;
export declare function splitCodeWithArbitraryVariants(_: string): string[];
// #endregion

// #region Variables
export declare const arbitraryPropertyRE: RegExp;
export declare const quotedArbitraryValuesRE: RegExp;
// #endregion