/**
 * Generated by tsnapi — public API snapshot of `@unocss/transformer-attributify-jsx`
 */
// #region Interfaces
export interface AttributifyResolverParams {
  code: MagicString;
  id: string;
  uno: UnoGenerator<object>;
  isBlocked: (_: string) => boolean;
}
export interface ResolverFilterPattern {
  pattern: string | RegExp;
  resolver: ResolverType;
}
export interface TransformerAttributifyJsxOptions {
  blocklist?: (string | RegExp)[];
  include?: IncludePattern;
  exclude?: FilterPattern;
}
// #endregion

// #region Types
export type FilterPattern = Array<string | RegExp> | string | RegExp | null;
export type IncludePattern = Array<string | RegExp | ResolverFilterPattern> | string | RegExp | ResolverFilterPattern | null;
export type ResolverType = 'oxc' | 'regex';
// #endregion

// #region Default Export
declare function _default(_?: TransformerAttributifyJsxOptions): SourceCodeTransformer;
export default _default
// #endregion