import { Rule } from '@unocss/core'
import {
  alignContents,
  alignItems,
  alignSelfs,
  appearance,
  appearances,
  aspectRatio,
  bgColors,
  borders,
  boxShadows,
  boxSizing,
  breaks as wordBreaks,
  contents,
  cursors,
  displays,
  fillColors,
  flexBase,
  flexDirections,
  floats,
  fontSizes,
  fontSmoothings,
  fontStyles,
  fontWeights,
  fontsFamilies,
  gaps,
  gridBase,
  gridTemplates,
  insets,
  justifies,
  justifyItems,
  justifySelfs,
  leadings,
  margins,
  opacity,
  orders,
  outline,
  overflows,
  paddings,
  placeContents,
  placeItems,
  placeSelfs,
  placeholder,
  pointerEvents,
  positions,
  questionMark,
  resizes,
  rings,
  sizes,
  tabSizes,
  textAligns,
  textColors,
  textDecorationColors,
  textDecorationLengths,
  textDecorationOffsets,
  textDecorationStyles,
  textDecorations,
  textIndents,
  textOverflows,
  textShadows,
  textStrokeColors,
  textStrokeWidths,
  trackings,
  transforms,
  transitions,
  userSelects,
  verticalAligns,
  whitespaces,
  wordSpacings,
  zIndexes,
} from '@unocss/preset-mini/rules'
import { container } from './container'
import { bgAttachments, bgBlendModes, bgClips, bgGradients, bgImages, bgOrigins, bgPositions, bgSizes, bgRepeats } from './background'
import { filters } from './filters'
import { mixBlendModes } from './shadow'
import { spaces } from './spacing'
import { screenReadersAccess, textTransforms, hyphens, writingModes, writingOrientations, isolations, objectPositions } from './static'
import { tables } from './table'
import { listStyle, caretColors, boxDecorationBreaks, caretOpacity, imageRenderings, overscrolls } from './behaviors'
import { animations } from './animation'
import { cssVariables } from './variables'
import { divides } from './divide'
import { lineClamps } from './line-clamp'
import { fontVariantNumeric } from './typography'

export const rules: Rule[] = [
  cssVariables,

  container,
  screenReadersAccess,
  pointerEvents,
  appearances,
  positions,
  insets,
  lineClamps,
  isolations,
  zIndexes,
  orders,
  gridBase,
  floats,
  margins,
  boxSizing,
  displays,
  aspectRatio,
  sizes,
  flexBase,
  tables,
  transforms,
  animations,
  cursors,
  // touchAction,
  userSelects,
  resizes,
  // scrolls,
  listStyle,
  appearance,
  // columns,
  // breaks,
  gridTemplates,
  flexDirections,
  placeContents,
  placeItems,
  alignContents,
  alignItems,
  justifies,
  justifyItems,
  gaps,
  spaces,
  divides,
  placeSelfs,
  alignSelfs,
  justifySelfs,
  overflows,
  overscrolls,
  // scrollBehavior,
  textOverflows,
  whitespaces,
  wordBreaks,
  borders,
  bgColors,
  bgImages,
  bgGradients,
  boxDecorationBreaks,
  bgSizes,
  bgAttachments,
  bgClips,
  bgPositions,
  bgRepeats,
  bgOrigins,
  fillColors,
  // strokes, // color, width
  objectPositions,
  paddings,
  textAligns,
  textIndents,
  verticalAligns,
  fontsFamilies,
  fontSizes,
  fontWeights,
  textTransforms,
  fontStyles,
  fontVariantNumeric,
  leadings,
  wordSpacings,
  trackings,
  textColors,
  textDecorations,
  textDecorationColors,
  textDecorationStyles,
  textDecorationLengths,
  textDecorationOffsets,
  fontSmoothings,
  tabSizes,
  textStrokeWidths,
  textStrokeColors,
  textShadows,
  hyphens,
  writingModes,
  writingOrientations,
  placeholder,
  caretColors,
  caretOpacity,
  // accentColors,
  opacity,
  bgBlendModes,
  mixBlendModes,
  boxShadows,
  outline,
  // outline-width
  rings,
  imageRenderings,
  filters,
  transitions,
  // willChange,
  contents,

  // should be the last
  questionMark,
].flat(1)
