/**
 * Generated by tsnapi — public API snapshot of `@unocss/vite`
 */
// #region Interfaces
export interface UnocssVitePluginAPI {
  getContext: () => UnocssPluginContext<VitePluginConfig>;
  getMode: () => VitePluginConfig['mode'];
}
export interface VitePluginConfig<Theme extends object = object> extends UserConfig<Theme> {
  inspector?: boolean;
  mode?: 'global' | 'per-module' | 'vue-scoped' | 'dist-chunk' | 'shadow-dom';
  transformCSS?: boolean | 'pre' | 'post';
  postcss?: boolean;
  hmrTopLevelAwait?: boolean;
  fetchMode?: 'cors' | 'navigate' | 'no-cors' | 'same-origin';
  checkImport?: boolean;
}
// #endregion

// #region Functions
export declare function ChunkModeBuildPlugin(_: UnocssPluginContext): Plugin;
export declare function defineConfig<Theme extends object>(_: VitePluginConfig<Theme>): VitePluginConfig<Theme>;
export declare function GlobalModeBuildPlugin(_: UnocssPluginContext<VitePluginConfig>): Plugin[];
export declare function GlobalModeDevPlugin(_: UnocssPluginContext): Plugin[];
export declare function GlobalModePlugin(_: UnocssPluginContext): import("vite").Plugin<any>[];
export declare function PerModuleModePlugin(_: UnocssPluginContext): Plugin[];
export declare function VueScopedPlugin(_: UnocssPluginContext): Plugin;
// #endregion

// #region Default Export
declare function _default<Theme extends object>(_?: VitePluginConfig<Theme> | string, _?: UserConfigDefaults): Plugin[];
export default _default
// #endregion