/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-attributify`
 */
// #region Interfaces
export interface AttributifyAttributes extends Partial<Record<AttributifyNames, string | boolean>> {}
export interface AttributifyOptions extends PresetOptions {
  strict?: boolean;
  prefix?: string;
  prefixedOnly?: boolean;
  nonValuedAttribute?: boolean;
  ignoreAttributes?: string[];
  trueToNonValued?: boolean;
}
// #endregion

// #region Types
export type AttributifyNames<Prefix extends string = ''> = `${Prefix}${BasicAttributes}` | `${Prefix}${PseudoPrefix}:${BasicAttributes}`;
export type BasicAttributes = SpecialSingleWord | TwoStringsComposition | SeparateEnabled;
export type PseudoPrefix = 'active' | 'before' | 'after' | 'dark' | 'light' | 'first' | 'last' | 'focus' | 'hover' | 'link' | 'print' | 'root' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'enabled' | 'disabled' | 'all' | 'children';
export type SeparateEnabled = 'align' | 'animate' | 'backdrop' | 'bg' | 'blend' | 'border' | 'box' | 'container' | 'content' | 'cursor' | 'display' | 'divide' | 'filter' | 'flex' | 'font' | 'fw' | 'gap' | 'gradient' | 'grid' | 'h' | 'icon' | 'items' | 'justify' | 'list' | 'm' | 'op' | 'opacity' | 'order' | 'outline' | 'overflow' | 'p' | 'place' | 'pos' | 'position' | 'ring' | 'select' | 'shadow' | 'size' | 'space' | 'table' | 'text' | 'transform' | 'transition' | 'underline' | 'w' | 'z' | PseudoPrefix;
export type SpecialSingleWord = 'container' | 'flex' | 'block' | 'inline' | 'table' | 'isolate' | 'absolute' | 'relative' | 'fixed' | 'sticky' | 'static' | 'visible' | 'invisible' | 'grow' | 'shrink' | 'antialiased' | 'italic' | 'ordinal' | 'overline' | 'underline' | 'uppercase' | 'lowercase' | 'capitalize' | 'truncate' | 'border' | 'rounded' | 'outline' | 'ring' | 'shadow' | 'blur' | 'grayscale' | 'invert' | 'sepia' | 'transition' | 'resize' | 'transform' | 'filter';
export type TwoStringsComposition = `${TwoStringsCompositionPrefix}${TwoStringsCompositionSuffix}` | 'ha' | 'wa';
export type TwoStringsCompositionPrefix = 'm' | 'p';
export type TwoStringsCompositionSuffix = 'r' | 'b' | 'l' | 't' | 'a' | 'x' | 'y';
// #endregion

// #region Functions
export declare function autocompleteExtractorAttributify(_?: AttributifyOptions): AutoCompleteExtractor;
export declare function extractorAttributify(_?: AttributifyOptions): Extractor;
export declare function variantAttributify(_?: AttributifyOptions): VariantObject;
// #endregion

// #region Variables
export declare const defaultIgnoreAttributes: string[];
export declare const presetAttributify: import("@unocss/core").PresetFactory<object, AttributifyOptions>;
export declare const variantsRE: RegExp;
// #endregion

// #region Default Export
declare const _default: import("@unocss/core").PresetFactory<object, AttributifyOptions>;
export default _default
// #endregion