/**
 * Generated by tsnapi — public API snapshot of `@unocss/twoslash`
 */
// #region Interfaces
export interface CreateTwoslashUnoCSSOptions {
  configPath?: string;
  preprocess?: (_: string) => string;
}
// #endregion

// #region Functions
export declare function createTwoslasher(_?: CreateTwoslashUnoCSSOptions): TwoslashGenericFunction;
// #endregion