import process from 'node:process'
import { beforeAll } from 'vitest'

beforeAll(() => {
  const originalStderrWrite = process.stderr.write
  process.stderr.write = (chunk, ...args) => {
    // The preflights styles generated by preset-wind3 contain empty CSS variables (e.g., --un-pan-x: ;)
    // which is legal in standard CSS, but the CSS parser used by jsdom does not currently support this syntax
    // so it will throw a "Could not parse CSS stylesheet" error.
    if (typeof chunk === 'string' && chunk.includes('Could not parse CSS stylesheet')) {
      return true
    }
    // @ts-expect-error compatible
    return originalStderrWrite.call(process.stderr, chunk, ...args)
  }
})
