/**
 * Generated by tsnapi — public API snapshot of `@unocss/transformer-directives`
 */
// #region Interfaces
export interface TransformerDirectivesContext {
  code: MagicString;
  uno: UnoGenerator;
  options: TransformerDirectivesOptions;
  applyVariable: string[];
  offset?: number;
  filename?: string;
}
export interface TransformerDirectivesOptions {
  enforce?: SourceCodeTransformer['enforce'];
  throwOnMissing?: boolean;
  applyVariable?: false | string | string[];
}
// #endregion

// #region Default Export
declare function _default(_?: TransformerDirectivesOptions): SourceCodeTransformer;
export default _default
// #endregion