/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Analyzer: typeof import('./components/Analyzer.vue')['default']
    AnalyzerItem: typeof import('./components/AnalyzerItem.vue')['default']
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    Copy: typeof import('./components/Copy.vue')['default']
    FileIcon: typeof import('./components/FileIcon.vue')['default']
    ModuleId: typeof import('./components/ModuleId.vue')['default']
    ModuleInfo: typeof import('./components/ModuleInfo.vue')['default']
    ModuleTreeNode: typeof import('./components/ModuleTreeNode.vue')['default']
    NarBar: typeof import('./components/NarBar.vue')['default']
    Overview: typeof import('./components/Overview.vue')['default']
    OverviewTabs: typeof import('./components/OverviewTabs.vue')['default']
    ReplPlayground: typeof import('./components/ReplPlayground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    StatusBar: typeof import('./components/StatusBar.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}

// For TSX support
declare global {
  const Analyzer: typeof import('./components/Analyzer.vue')['default']
  const AnalyzerItem: typeof import('./components/AnalyzerItem.vue')['default']
  const CodeMirror: typeof import('./components/CodeMirror.vue')['default']
  const Copy: typeof import('./components/Copy.vue')['default']
  const FileIcon: typeof import('./components/FileIcon.vue')['default']
  const ModuleId: typeof import('./components/ModuleId.vue')['default']
  const ModuleInfo: typeof import('./components/ModuleInfo.vue')['default']
  const ModuleTreeNode: typeof import('./components/ModuleTreeNode.vue')['default']
  const NarBar: typeof import('./components/NarBar.vue')['default']
  const Overview: typeof import('./components/Overview.vue')['default']
  const OverviewTabs: typeof import('./components/OverviewTabs.vue')['default']
  const ReplPlayground: typeof import('./components/ReplPlayground.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Sidebar: typeof import('./components/Sidebar.vue')['default']
  const StatusBar: typeof import('./components/StatusBar.vue')['default']
  const Tabs: typeof import('./components/Tabs.vue')['default']
  const TitleBar: typeof import('./components/TitleBar.vue')['default']
}