/**
 * Generated by tsnapi — public API snapshot of `@unocss/core`
 */
// #region Interfaces
export interface AutoCompleteExtractor {
  name: string;
  extract: (_: AutoCompleteExtractorContext) => Awaitable<AutoCompleteExtractorResult | null>;
  order?: number;
}
export interface AutoCompleteExtractorContext {
  content: string;
  cursor: number;
}
export interface AutoCompleteExtractorResult {
  extracted: string;
  resolveReplacement: (_: string) => Replacement;
  transformSuggestions?: (_: string[]) => string[];
}
export interface BaseContext<Theme extends object = object> {
  generator: UnoGenerator<Theme>;
  theme: Theme;
}
export interface BlocklistMeta {
  message?: string | ((_: string) => string);
}
export interface CliEntryItem {
  patterns: string[];
  outFile: string;
  rewrite?: boolean;
  splitCss?: boolean | 'multi' | 'single';
}
export interface CliOptions {
  cli?: {
    entry?: Arrayable<CliEntryItem>;
  };
}
export interface ConfigBase<Theme extends object = object> {
  rules?: Rule<Theme>[];
  separators?: Arrayable<string>;
  variantApplyOrder?: 'right-to-left' | 'left-to-right';
  variants?: Variant<Theme>[];
  shortcuts?: UserShortcuts<Theme>;
  blocklist?: BlocklistRule[];
  safelist?: (string | ((context: SafeListContext<Theme>) => Arrayable<string>))[];
  extractors?: Extractor[];
  extractorDefault?: Extractor | null | false;
  preflights?: Preflight<Theme>[];
  theme?: Theme;
  layers?: Record<string, number>;
  outputToCssLayers?: boolean | OutputCssLayersOptions;
  sortLayers?: (_: string[]) => string[];
  preprocess?: Arrayable<Preprocessor>;
  postprocess?: Arrayable<Postprocessor>;
  extendTheme?: Arrayable<ThemeExtender<Theme>>;
  presets?: (PresetOrFactoryAwaitable<Theme> | PresetOrFactoryAwaitable<Theme>[])[];
  autocomplete?: {
    templates?: Arrayable<AutoCompleteFunction | AutoCompleteTemplate>;
    extractors?: Arrayable<AutoCompleteExtractor>;
    shorthands?: Record<string, string | string[]>;
  };
  configResolved?: (_: ResolvedConfig<Theme>) => void;
  details?: boolean;
  content?: ContentOptions;
  transformers?: SourceCodeTransformer[];
  processors?: CSSProcessor<Theme>[];
}
export interface ContentOptions {
  filesystem?: string[];
  inline?: (string | {
    code: string;
    id?: string;
  } | (() => Awaitable<string | {
    code: string;
    id?: string;
  }>))[];
  pipeline?: false | {
    include?: FilterPattern;
    exclude?: FilterPattern;
  };
}
export interface ControlSymbols {
  shortcutsNoMerge: typeof SymbolShortcutsNoMerge;
  noMerge: typeof SymbolNoMerge;
  noScope: typeof SymbolNoScope;
  variants: typeof SymbolVariants;
  parent: typeof SymbolParent;
  selector: typeof SymbolSelector;
  layer: typeof SymbolLayer;
  sort: typeof SymbolSort;
  body: typeof SymbolBody;
}
export interface ControlSymbolsValue {
  [SymbolShortcutsNoMerge]: true;
  [SymbolNoMerge]: true;
  [SymbolNoScope]: true;
  [SymbolVariants]: VariantHandler[] | ((_: VariantHandler[]) => VariantHandler[]);
  [SymbolParent]: string;
  [SymbolSelector]: (_: string) => string;
  [SymbolLayer]: string;
  [SymbolSort]: number;
  [SymbolBody]: string;
}
export interface CSSProcessor<Theme extends object = object> {
  name: string;
  order?: number;
  process: (_: string, _: CSSProcessorContext<Theme>) => Awaitable<string>;
}
export interface CSSProcessorContext<Theme extends object = object> {
  layer: string;
  theme: Theme;
  envMode: 'dev' | 'build';
}
export interface ExtendedTokenInfo<Theme extends object = object> {
  data: StringifiedUtil<Theme>[];
  count: number;
}
export interface Extractor {
  name: string;
  order?: number;
  extract?: (_: ExtractorContext) => Awaitable<Set<string> | CountableSet<string> | string[] | undefined | void>;
}
export interface ExtractorContext {
  readonly original: string;
  code: string;
  id?: string;
  extracted: Set<string> | CountableSet<string>;
  envMode?: 'dev' | 'build';
}
export interface GenerateOptions<T extends boolean> {
  id?: string;
  preflights?: boolean;
  safelist?: boolean;
  minify?: boolean;
  scope?: string;
  extendedInfo?: T;
}
export interface GenerateResult<T = Set<string>> {
  css: string;
  layers: string[];
  getLayer: (_?: string) => string | undefined;
  getLayers: (_?: string[], _?: string[]) => string;
  setLayer: (_: string, _: (_: string) => Promise<string>) => Promise<string>;
  matched: T;
}
export interface GeneratorOptions {
  mergeSelectors?: boolean;
  warn?: boolean;
}
export interface HighlightAnnotation {
  offset: number;
  length: number;
  className: string;
}
export interface OutputCssLayersOptions {
  cssLayerName?: (_: string) => string | undefined | null;
  allLayers?: boolean;
}
export interface PluginOptions {
  configFile?: string | false;
  configDeps?: string[];
  transformers?: SourceCodeTransformer[];
  content?: ContentOptions;
}
export interface Preflight<Theme extends object = object> {
  getCSS: (_: PreflightContext<Theme>) => Promise<string | undefined> | string | undefined;
  layer?: string;
}
export interface PreflightContext<Theme extends object = object> extends BaseContext<Theme> {}
export interface Preset<Theme extends object = object> extends ConfigBase<Theme> {
  name: string;
  enforce?: 'pre' | 'post';
  options?: PresetOptions;
  prefix?: string | string[];
  layer?: string;
  api?: any;
  meta?: Record<string, any>;
  docs?: string;
}
export interface Replacement {
  start: number;
  end: number;
  replacement: string;
}
export interface ResolvedConfig<Theme extends object = object> extends Omit<RequiredByKey<UserConfig<Theme>, 'mergeSelectors' | 'theme' | 'rules' | 'variants' | 'layers' | 'extractors' | 'blocklist' | 'safelist' | 'preflights' | 'sortLayers' | 'variantApplyOrder'>, 'rules' | 'shortcuts' | 'autocomplete' | 'presets'> {
  presets: Preset<Theme>[];
  shortcuts: Shortcut<Theme>[];
  variants: VariantObject<Theme>[];
  preprocess: Preprocessor[];
  postprocess: Postprocessor[];
  rulesSize: number;
  rules: readonly Rule<Theme>[];
  rulesDynamic: readonly DynamicRule<Theme>[];
  rulesDynamicFilter?: {
    fallback: readonly DynamicRule<Theme>[];
    filters: readonly RegExp[];
  };
  rulesStaticMap: Record<string, StaticRule | undefined>;
  autocomplete: {
    templates: (AutoCompleteFunction | AutoCompleteTemplate)[];
    extractors: AutoCompleteExtractor[];
    shorthands: Record<string, string>;
  };
  separators: string[];
}
export interface RuleContext<Theme extends object = object> {
  rawSelector: string;
  currentSelector: string;
  generator: UnoGenerator<Theme>;
  symbols: ControlSymbols;
  theme: Theme;
  variantHandlers: VariantHandler[];
  variantMatch: VariantMatchedResult<Theme>;
  constructCSS: (_: CSSEntries | CSSObject, _?: string) => string;
  rules?: Rule<Theme>[];
  shortcuts?: Shortcut<Theme>[];
  variants?: Variant<Theme>[];
}
export interface RuleMeta {
  layer?: string;
  noMerge?: boolean;
  noScope?: boolean;
  sort?: number;
  autocomplete?: Arrayable<AutoCompleteTemplate>;
  prefix?: string | string[];
  internal?: boolean;
  __hash?: string;
  __index?: number;
  custom?: Record<string, any>;
}
export interface SafeListContext<Theme extends object = object> extends BaseContext<Theme> {}
export interface ShortcutInlineValue {
  handles: VariantHandler[];
  value: ShortcutValue;
}
export interface SourceCodeTransformer {
  name: string;
  docs?: string;
  enforce?: SourceCodeTransformerEnforce;
  idFilter?: (_: string) => boolean;
  codeFilter?: (_: string, _: string) => boolean;
  transform: (_: MagicString, _: string, _: UnocssPluginContext) => Awaitable<{
    highlightAnnotations?: HighlightAnnotation[];
  } | void>;
}
export interface SourceMap {
  file?: string;
  mappings?: string;
  names?: string[];
  sources?: string[];
  sourcesContent?: string[];
  version?: number;
}
export interface SuggestResult {
  suggestions: [string, string][];
  resolveReplacement: (_: string) => Replacement;
}
export interface UnocssPluginContext<Config extends UserConfig = UserConfig> {
  ready: Promise<LoadConfigResult<Config>>;
  uno: UnoGenerator;
  tokens: Set<string>;
  modules: BetterMap<string, string>;
  affectedModules: Set<string>;
  tasks: Promise<any>[];
  flushTasks: () => Promise<any>;
  filter: (_: string, _: string) => boolean;
  extract: (_: string, _?: string) => Promise<void>;
  reloadConfig: () => Promise<LoadConfigResult<Config>>;
  getConfig: () => Promise<Config>;
  onReload: (_: () => void) => void;
  invalidate: () => void;
  onInvalidate: (_: () => void) => void;
  root: string;
  updateRoot: (_: string) => Promise<LoadConfigResult<Config>>;
  getConfigFileList: () => string[];
  getVMPRegexes: () => Promise<{
    prefix: string;
    RESOLVED_ID_WITH_QUERY_RE: RegExp;
    RESOLVED_ID_RE: RegExp;
  }>;
}
export interface Unsubscribe {
  (): void;
}
export interface UserConfig<Theme extends object = object> extends ConfigBase<Theme>, UserOnlyOptions<Theme>, GeneratorOptions, PluginOptions, CliOptions {}
export interface UserConfigDefaults<Theme extends object = object> extends ConfigBase<Theme>, UserOnlyOptions<Theme> {}
export interface UserOnlyOptions<Theme extends object = object> {
  theme?: Theme;
  shortcutsLayer?: string;
  envMode?: 'dev' | 'build';
  legacy?: {
    renderModernChunks: boolean;
  };
  virtualModulePrefix?: string;
}
export interface UtilObject {
  selector: string;
  entries: CSSEntries;
  parent: string | undefined;
  layer: string | undefined;
  sort: number | undefined;
  noMerge: boolean | undefined;
}
export interface VariantContext<Theme extends object = object> {
  rawSelector: string;
  generator: UnoGenerator<Theme>;
  theme: Theme;
}
export interface VariantHandler {
  handle?: (_: VariantHandlerContext, _: (_: VariantHandlerContext) => VariantHandlerContext) => VariantHandlerContext;
  matcher?: string;
  order?: number;
  selector?: (_: string, _: CSSEntries) => string | undefined;
  body?: (_: CSSEntries) => CSSEntries | undefined;
  parent?: string | [string, number] | undefined;
  sort?: number;
  layer?: string | undefined;
}
export interface VariantHandlerContext {
  prefix: string;
  selector: string;
  pseudo: string;
  entries: CSSEntries;
  parent?: string;
  parentOrder?: number;
  layer?: string;
  sort?: number;
  noMerge?: boolean;
  application?: object;
}
export interface VariantObject<Theme extends object = object> {
  name?: string;
  match: VariantFunction<Theme>;
  order?: number;
  multiPass?: boolean;
  autocomplete?: Arrayable<AutoCompleteFunction | AutoCompleteTemplate>;
}
// #endregion

// #region Types
export type ArgumentType<T> = T extends ((...args: infer A) => any) ? A : never;
export type Arrayable<T> = T | T[];
export type AutoCompleteFunction = (_: string) => Awaitable<string[]>;
export type AutoCompleteTemplate = string;
export type Awaitable<T> = T | Promise<T>;
export type BlocklistRule = BlocklistValue | [BlocklistValue, BlocklistMeta];
export type BlocklistValue = string | RegExp | ((_: string) => boolean | null | undefined);
export type ControlSymbolsEntry = ObjectToEntry<ControlSymbolsValue>;
export type CSSEntries = CSSEntry[];
export type CSSEntriesInput = (CSSEntry | ControlSymbolsEntry)[];
export type CSSEntry = [string, string | number | undefined, Arrayable<string>?];
export type CSSObject = Record<string, string | number | undefined>;
export type CSSObjectInput = CSSObject | Partial<ControlSymbolsValue>;
export type CSSValue = CSSObject | CSSEntries;
export type CSSValueInput = CSSObjectInput | CSSEntriesInput | CSSValue;
export type CSSValues = CSSValue | CSSValue[];
export type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]>; };
export type DynamicMatcher<Theme extends object = object> = (_: RegExpMatchArray, _: Readonly<RuleContext<Theme>>) => Awaitable<CSSValueInput | string | (CSSValueInput | string)[] | undefined> | Generator<CSSValueInput | string | undefined> | AsyncGenerator<CSSValueInput | string | undefined>;
export type DynamicRule<Theme extends object = object> = [RegExp, DynamicMatcher<Theme>, RuleMeta?];
export type DynamicShortcut<Theme extends object = object> = [RegExp, DynamicShortcutMatcher<Theme>, RuleMeta?];
export type DynamicShortcutMatcher<Theme extends object = object> = ((_: RegExpMatchArray, _: Readonly<RuleContext<Theme>>) => (string | ShortcutValue[] | undefined));
export type FilterPattern = ReadonlyArray<string | RegExp> | string | RegExp | null;
export type FlatObjectTuple<T> = { [K in keyof T]: T[K]; };
export type ObjectToEntry<T> = { [K in keyof T]: [K, T[K]]; }[keyof T];
export type ParsedUtil = readonly [index: number, raw: string, entries: CSSEntries, meta: RuleMeta | undefined, variantHandlers: VariantHandler[]];
export type PartialByKeys<T, K extends keyof T = keyof T> = FlatObjectTuple<Partial<Pick<T, Extract<keyof T, K>>> & Omit<T, K>>;
export type Postprocessor = (_: UtilObject) => void | UtilObject | (UtilObject | null | undefined)[];
export type PreparedRule = readonly [selector: [string, number][], body: string, noMerge: boolean];
export type Preprocessor = (_: string) => string | undefined;
export type PresetFactory<Theme extends object = object, PresetOptions extends object | undefined = undefined> = (_?: PresetOptions) => Preset<Theme>;
export type PresetFactoryAwaitable<Theme extends object = object, PresetOptions extends object | undefined = undefined> = (_?: PresetOptions) => Awaitable<Preset<Theme>>;
export type PresetOptions = Record<string, any>;
export type PresetOrFactory<Theme extends object = object> = Preset<Theme> | PresetFactory<Theme, any>;
export type PresetOrFactoryAwaitable<Theme extends object = object> = PresetOrFactory<Theme> | Promise<Preset<Theme>> | PresetFactoryAwaitable<Theme>;
export type RawUtil = readonly [index: number, rawCSS: string, meta: RuleMeta | undefined];
export type RequiredByKey<T, K extends keyof T = keyof T> = FlatObjectTuple<Required<Pick<T, Extract<keyof T, K>>> & Omit<T, K>>;
export type RestArgs<T> = Shift<ArgumentType<T>>;
export type Rule<Theme extends object = object> = DynamicRule<Theme> | StaticRule;
export type Shift<T> = T extends [_: any, ...args: infer A] ? A : never;
export type Shortcut<Theme extends object = object> = StaticShortcut | DynamicShortcut<Theme>;
export type ShortcutValue = string | CSSValue;
export type SourceCodeTransformerEnforce = 'pre' | 'post' | 'default';
export type StaticRule = [string, CSSObject | CSSEntries | (CSSValueInput | string)[], RuleMeta?];
export type StaticShortcut = [string, string | ShortcutValue[], RuleMeta?];
export type StaticShortcutMap = Record<string, string | ShortcutValue[]>;
export type StringifiedUtil<Theme extends object = object> = readonly [index: number, selector: string | undefined, body: string, parent: string | undefined, meta: RuleMeta | undefined, context: RuleContext<Theme> | undefined, noMerge: boolean | undefined];
export type ThemeExtender<Theme extends object = object> = (_: Theme, _: Readonly<ResolvedConfig<Theme>>) => Theme | void;
export type ToArray<T> = T extends (infer U)[] ? U[] : T[];
export type UserShortcuts<Theme extends object = object> = StaticShortcutMap | (StaticShortcut | DynamicShortcut<Theme> | StaticShortcutMap)[];
export type Variant<Theme extends object = object> = VariantFunction<Theme> | VariantObject<Theme>;
export type VariantFunction<Theme extends object = object> = (_: string, _: Readonly<VariantContext<Theme>>) => Awaitable<string | VariantHandler | VariantHandler[] | undefined>;
export type VariantMatchedResult<Theme extends object = object> = [raw: string, current: string, variantHandlers: VariantHandler[], variants: Set<Variant<Theme>>];
// #endregion

// #region Classes
export declare class BetterMap<K, V> extends Map<K, V> {
  getFallback(_: K, _: V): V;
  map<R>(_: (_: V, _: K) => R): R[];
  flatMap<R extends readonly unknown[]>(_: (_: V, _: K) => R): R[number][];
}
export declare class CountableSet<K> extends Set<K> {
  _map: Map<K, number>;
  constructor(_?: Iterable<K>);
  add(_: K): this;
  delete(_: K): boolean;
  clear(): void;
  getCount(_: K): number;
  setCount(_: K, _: number): this;
}
export declare class Emitter<Events extends EventsMap = DefaultEvents> {
  events: Partial<{ [E in keyof Events]: Events[E][]; }>;
  on<K extends keyof Events>(this: this, _: K, _: Events[K]): Unsubscribe;
  emit<K extends keyof Events>(this: this, _: K, ..._: Parameters<Events[K]>): void;
}
export declare class TwoKeyMap<K1, K2, V> {
  _map: Map<K1, Map<K2, V>>;
  get(_: K1, _: K2): V | undefined;
  getFallback(_: K1, _: K2, _: V): V;
  set(_: K1, _: K2, _: V): this;
  has(_: K1, _: K2): boolean | undefined;
  delete(_: K1, _: K2): boolean;
  deleteTop(_: K1): boolean;
  map<T>(_: (_: V, _: K1, _: K2) => T): T[];
}
export declare class UnoGenerator<Theme extends object = object> extends UnoGeneratorInternal<Theme> {
  constructor(_?: UserConfig<Theme>, _?: UserConfigDefaults<Theme>);
}
// #endregion

// #region Functions
export declare function clearIdenticalEntries(_: CSSEntries): CSSEntries;
export declare function clone<T>(_: T): T;
export declare function collapseVariantGroup(_: string, _: string[]): string;
export declare function createGenerator<Theme extends object = object>(_?: UserConfig<Theme>, _?: UserConfigDefaults<Theme>): Promise<UnoGenerator<Theme>>;
export declare function createNanoEvents<Events extends EventsMap = DefaultEvents>(): Emitter<Events>;
export declare function definePreset<Options extends object | undefined = undefined, Theme extends object = object>(_: PresetFactory<Theme, Options>): PresetFactory<Theme, Options>;
export declare function definePreset<Options extends object | undefined = undefined, Theme extends object = object>(_: PresetFactoryAwaitable<Theme, Options>): PresetFactoryAwaitable<Theme, Options>;
export declare function definePreset<Theme extends object = object>(_: Preset<Theme>): Preset<Theme>;
export declare function entriesToCss(_?: CSSEntries): string;
export declare function escapeRegExp(_: string): string;
export declare function escapeSelector(_: string): string;
export declare function expandVariantGroup(_: string, _?: string[], _?: number): string;
export declare function expandVariantGroup(_: MagicString, _?: string[], _?: number): MagicString;
export declare function hasScopePlaceholder(_: string): boolean;
export declare function isAttributifySelector(_: string): RegExpMatchArray | null;
export declare function isCountableSet<T = string>(_: any): value is CountableSet<T>;
export declare function isObject(_: any): item is Record<string, any>;
export declare function isRawUtil(_: ParsedUtil | RawUtil | StringifiedUtil): util is RawUtil;
export declare function isStaticRule(_: Rule<any>): rule is StaticRule;
export declare function isStaticShortcut(_: Shortcut<any>): sc is StaticShortcut;
export declare function isString(_: any): s is string;
export declare function isValidSelector(_?: string): selector is string;
export declare function makeRegexClassGroup(_?: string[]): RegExp;
export declare function mergeConfigs<Theme extends object = object>(_: UserConfig<Theme>[]): UserConfig<Theme>;
export declare function mergeDeep<T>(_: T, _: DeepPartial<T>, _?: boolean): T;
export declare function noop(): void;
export declare function normalizeCSSEntries(_: string | CSSEntriesInput | CSSObjectInput): string | CSSEntries;
export declare function normalizeCSSValues(_: CSSValueInput | string | (CSSValueInput | string)[]): (string | CSSEntries)[];
export declare function normalizeVariant(_: Variant<any>): VariantObject<any>;
export declare function notNull<T>(_: T | null | undefined): value is T;
export declare function parseVariantGroup(_: string | MagicString, _?: string[], _?: number): {
  prefixes: string[];
  hasChanged: boolean;
  groupsByOffset: Map<number, VariantGroup>;
  readonly expanded: string;
};
export declare function resolveConfig<Theme extends object = object>(_?: UserConfig<Theme>, _?: UserConfigDefaults<Theme>): Promise<ResolvedConfig<Theme>>;
export declare function resolvePreset<Theme extends object = object>(_: PresetOrFactoryAwaitable<Theme>): Promise<Preset<Theme>>;
export declare function resolvePresets<Theme extends object = object>(_: PresetOrFactoryAwaitable<Theme>): Promise<Preset<Theme>[]>;
export declare function resolveShortcuts<Theme extends object = object>(_: UserShortcuts<Theme>): Shortcut<Theme>[];
export declare function splitVariantGroupBody(_: string): {
  index: number;
  value: string;
}[];
export declare function toArray<T>(_?: T | T[]): T[];
export declare function toEscapedSelector(_: string): string;
export declare function uniq<T>(_: T[]): T[];
export declare function uniqueBy<T>(_: readonly T[], _: (_: T, _: T) => boolean): T[];
export declare function warnOnce(_: string): void;
export declare function withLayer<T extends object>(_: string, _: Rule<T>[]): Rule<T>[];
// #endregion

// #region Variables
export declare const attributifyRE: RegExp;
export declare const cssIdRE: RegExp;
export declare const DEFAULT_LAYERS: {
  imports: number;
  preflights: number;
  shortcuts: number;
  default: number;
};
export declare const defaultSplitRE: RegExp;
export declare const e: typeof escapeSelector;
export declare const extractorDefault: Extractor;
export declare const extractorSplit: Extractor;
export declare const LAYER_DEFAULT: string;
export declare const LAYER_IMPORTS: string;
export declare const LAYER_PREFLIGHTS: string;
export declare const LAYER_SHORTCUTS: string;
export declare const regexScopePlaceholder: RegExp;
export declare const splitWithVariantGroupRE: RegExp;
export declare const symbols: ControlSymbols;
export declare const validateFilterRE: RegExp;
export declare const VirtualKey: string;
// #endregion

// #region Referenced (internal)
interface DefaultEvents extends EventsMap {
  [event: string]: (..._: any) => void;
}
type EventsMap = Record<string, any>;
declare class UnoGeneratorInternal<Theme extends object = object> {
  userConfig: UserConfig<Theme>;
  defaults: UserConfigDefaults<Theme>;
  readonly version: string;
  readonly events: Emitter<{
    config: (config: ResolvedConfig<Theme>) => void;
  }>;
  config: ResolvedConfig<Theme>;
  private tokenProcessor;
  protected constructor(_?: UserConfig<Theme>, _?: UserConfigDefaults<Theme>);
  static create<Theme extends object = object>(_?: UserConfig<Theme>, _?: UserConfigDefaults<Theme>): Promise<UnoGeneratorInternal<Theme>>;
  setConfig(_?: UserConfig<Theme>, _?: UserConfigDefaults<Theme>): Promise<void>;
  applyExtractors(_: string, _?: string, _?: Set<string>): Promise<Set<string>>;
  applyExtractors(_: string, _?: string, _?: CountableSet<string>): Promise<CountableSet<string>>;
  makeContext(_: string, _: VariantMatchedResult<Theme>): RuleContext<Theme>;
  resetTokenProcessing(): void;
  getParentOrder(_: string): number | undefined;
  getActivatedRules(): ReadonlySet<Rule<Theme>>;
  getCachedTokens(_: string): string[];
  getCachedAliases(_: string): string[] | undefined;
  blockTokens(_: Iterable<string>): void;
  invalidateToken(_: string): void;
  parseToken(_: string, _?: string): Promise<StringifiedUtil<Theme>[] | undefined | null>;
  generate(_: string | Set<string> | CountableSet<string> | string[], _?: GenerateOptions<false>): Promise<GenerateResult<Set<string>>>;
  generate(_: string | Set<string> | CountableSet<string> | string[], _?: GenerateOptions<true>): Promise<GenerateResult<Map<string, ExtendedTokenInfo<Theme>>>>;
  matchVariants(_: string, _?: string): Promise<readonly VariantMatchedResult<Theme>[]>;
  private applyVariants;
  constructCustomCSS(_: Readonly<RuleContext<Theme>>, _: CSSObject | CSSEntries, _?: string): string;
  parseUtil(_: string | VariantMatchedResult<Theme>, _: RuleContext<Theme>, _?: boolean, _?: string | string[] | undefined): Promise<(ParsedUtil | RawUtil)[] | undefined>;
  private resolveCSSResult;
  stringifyUtil(_?: ParsedUtil | RawUtil, _?: RuleContext<Theme>): StringifiedUtil<Theme>[] | undefined;
  expandShortcut(_: string, _: RuleContext<Theme>, _?: number, _?: boolean): Promise<[(string | ShortcutInlineValue)[], RuleMeta | undefined] | undefined>;
  stringifyShortcuts(_: VariantMatchedResult<Theme>, _: RuleContext<Theme>, _: (string | ShortcutInlineValue)[], _?: RuleMeta): Promise<StringifiedUtil<Theme>[] | undefined>;
  isBlocked(_: string): boolean;
  getBlocked(_: string): [BlocklistValue, BlocklistMeta | undefined] | undefined;
}
interface VariantGroup {
  length: number;
  items: HighlightAnnotation[];
}
// #endregion