import { createGenerator } from '@unocss/core'
import { describe, expect, it, vi } from 'vitest'
import { presetWind4 } from '../../../packages-presets/preset-wind4'
import { getPrettiedCSS, getPrettiedMarkdown } from '../src/utils/css'

describe('getPrettiedMarkdown', () => {
  it('shows a resolved default theme value while preserving the generated declaration', async () => {
    const uno = await createGenerator({
      presets: [presetWind4({ preflights: { reset: false } })],
    })

    await expect(getPrettiedMarkdown(uno, 'p-4', -1)).resolves.toContain(`.p-4 {
  padding: calc(var(--spacing) * 4); /* 1rem */
}`)
  })

  it('uses the current custom theme value', async () => {
    const uno = await createGenerator({
      presets: [presetWind4({ preflights: { reset: false } })],
      theme: {
        spacing: { DEFAULT: '0.5rem' },
      },
    })

    await expect(getPrettiedMarkdown(uno, 'p-4', -1)).resolves.toContain(`.p-4 {
  padding: calc(var(--spacing) * 4); /* 2rem */
}`)
  })

  it('does not show a resolved value when the theme cannot resolve it', async () => {
    const uno = await createGenerator({
      rules: [
        ['p-4', { padding: 'var(--spacing)' }],
      ],
    })

    await expect(getPrettiedMarkdown(uno, 'p-4', -1)).resolves.toContain(`.p-4 {
  padding: var(--spacing);
}`)
  })

  it('resolves custom preflight theme variables', async () => {
    const uno = await createGenerator({
      preflights: [{ getCSS: () => ':root { --brand: 4rem }' }],
      rules: [['p-brand', { padding: 'var(--brand)' }]],
    })

    await expect(getPrettiedMarkdown(uno, 'p-brand', -1)).resolves.toContain(`.p-brand {
  padding: var(--brand); /* 4rem */
}`)
  })

  it('does not annotate generated runtime variables or mixed declarations', async () => {
    const uno = await createGenerator({
      presets: [presetWind4({ preflights: { reset: false } })],
    })

    for (const util of ['space-x-4', 'divide-x-4', 'text-red-500']) {
      const markdown = await getPrettiedMarkdown(uno, util, -1)
      // Layer markers are generated by the generator itself, ignore them.
      const annotations = markdown.replace(/\/\* layer:[^*]+\*\//g, '')
      expect(annotations, util).not.toContain('/*')
    }
  })

  it('resolves theme variables with a single generation per hover', async () => {
    const uno = await createGenerator({
      presets: [presetWind4({ preflights: { reset: false } })],
    })
    const generate = vi.spyOn(uno, 'generate')

    await getPrettiedCSS(uno, 'p-4', -1)

    expect(generate).toHaveBeenCalledTimes(1)
    expect(generate.mock.calls[0]?.[1]).toMatchObject({ preflights: true })
  })
})
