/**
 * Generated by tsnapi — public API snapshot of `@unocss/transformer-compile-class`
 */
// #region Interfaces
export interface CompileClassOptions {
  trigger?: string | RegExp;
  classPrefix?: string;
  hashFn?: (_: string) => string;
  alwaysHash?: boolean;
  keepUnknown?: boolean;
  layer?: string;
}
// #endregion

// #region Default Export
declare function _default(_?: CompileClassOptions): SourceCodeTransformer;
export default _default
// #endregion