/**
 * Generated by tsnapi — public API snapshot of `@unocss/runtime`
 */
// #region Interfaces
export interface RuntimeContext {
  uno: UnoGenerator;
  extract: (_: string | string[]) => Promise<void>;
  extractAll: (_?: Element) => Promise<void>;
  inspect: (_?: RuntimeInspectorCallback) => void;
  toggleObserver: (_?: boolean) => void;
  update: () => Promise<RuntimeGenerateResult>;
  presets: Record<string, Function>;
  version: string;
}
export interface RuntimeGenerateResult extends GenerateResult {
  getStyleElement: (_: string) => HTMLStyleElement | undefined;
  getStyleElements: () => Map<string, HTMLStyleElement>;
}
export interface RuntimeObserverConfig {
  target?: () => Element;
  attributeFilter?: Array<string>;
}
export interface RuntimeOptions {
  defaults?: UserConfigDefaults;
  autoPrefix?: boolean;
  cloakAttribute?: string;
  configResolved?: (_: UserConfig, _: UserConfigDefaults) => void;
  inject?: (_: HTMLStyleElement) => void;
  ready?: (_: RuntimeContext) => false | any;
  observer?: RuntimeObserverConfig;
  bypassDefined?: boolean;
  rootElement?: () => Element | undefined;
}
// #endregion

// #region Types
export type RuntimeInspectorCallback = (_: Element) => boolean;
// #endregion

// #region Functions
export declare function defineConfig<T extends object = Theme>(_: UserConfig<T>): UserConfig<T>;
// #endregion

// #region Default Export
declare function _default(_?: RuntimeOptions): Promise<void>;
export default _default
// #endregion