/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-rem-to-px`
 */
// #region Interfaces
export interface RemToPxOptions {
  baseFontSize?: number;
}
// #endregion

// #region Variables
export declare const presetRemToPx: import("@unocss/core").PresetFactory<object, RemToPxOptions>;
// #endregion

// #region Default Export
declare const _default: import("@unocss/core").PresetFactory<object, RemToPxOptions>;
export default _default
// #endregion