/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-icons/core`
 */
// #region Interfaces
export interface IconsAPI {
  encodeSvgForCss: typeof encodeSvgForCss;
  parseIconWithLoader: typeof parseIconWithLoader;
  createNodeLoader?: () => Promise<UniversalIconLoader | undefined>;
}
export interface IconsOptions {
  scale?: number;
  mode?: 'mask' | 'bg' | 'auto';
  prefix?: string | string[];
  extraProperties?: Record<string, string>;
  warn?: boolean;
  iconifyCollectionsNames?: string[];
  collections?: Record<string, (() => Awaitable<IconifyJSON>) | undefined | CustomIconLoader | InlineCollection>;
  layer?: string;
  customizations?: Omit<IconCustomizations, 'additionalProps' | 'trimCustomSvg'>;
  autoInstall?: boolean;
  collectionsNodeResolvePath?: string | string[];
  unit?: string;
  cdn?: string;
  customFetch?: (_: string) => Promise<any>;
  processor?: (_: CSSObject, _: Required<IconMeta>) => void;
}
// #endregion

// #region Functions
export declare function combineLoaders(_: UniversalIconLoader[]): UniversalIconLoader;
export declare function createCDNFetchLoader(_: (_: string) => Promise<any>, _: string, _?: Map<string, IconifyJSON | Promise<IconifyJSON>>): UniversalIconLoader;
export declare function createPresetIcons(_: (_: IconsOptions) => Promise<UniversalIconLoader>): import("@unocss/core").PresetFactory<object, IconsOptions>;
export declare function parseIconWithLoader(_: string, _: UniversalIconLoader, _?: IconifyLoaderOptions, _?: string[]): Promise<{
  collection: string;
  name: string;
  svg: string;
} | undefined>;
// #endregion

// #region Variables
export declare const icons: string[];
// #endregion