/**
 * Generated by tsnapi — public API snapshot of `@unocss/cli`
 */
// #region Functions
export declare function build(_: CliOptions): Promise<void[] | undefined>;
// #endregion

// #region Referenced (internal)
interface CliOptions extends CliGenericOptions {
  cwd?: string;
  patterns?: Array<string>;
  outFile?: string;
  watch?: boolean;
  config?: string;
  stdout?: boolean;
  rewrite?: boolean;
  writeTransformed?: boolean;
  debug?: boolean;
  splitCss?: boolean | 'multi' | 'single';
  preset?: 'wind3' | 'wind4';
}
// #endregion