/**
 * Generated by tsnapi — public API snapshot of `@unocss/webpack`
 */
// #region Interfaces
export interface WebpackPluginOptions<Theme extends object = object> extends UserConfig<Theme> {
  watch?: boolean;
}
// #endregion

// #region Functions
export declare function WebpackPlugin<Theme extends object>(_?: WebpackPluginOptions<Theme> | string, _?: UserConfigDefaults): WebpackPluginInstance;
// #endregion

// #region Default Export
declare function _default<Theme extends object>(_?: WebpackPluginOptions<Theme> | string, _?: UserConfigDefaults): WebpackPluginInstance;
export default _default
// #endregion