/**
 * Generated by tsnapi — public API snapshot of `@unocss/webpack/rspack`
 */
// #region Functions
export declare function UnoCSSRspackPlugin<Theme extends object>(_?: WebpackPluginOptions<Theme> | string, _?: UserConfigDefaults): RspackPluginInstance;
// #endregion