/**
 * Generated by tsnapi — public API snapshot of `@unocss/processor-lightningcss`
 */
// #region Interfaces
export interface ProcessorLightningCSSOptions extends Omit<TransformOptions<CustomAtRules>, 'code' | 'filename'> {}
// #endregion

// #region Default Export
export default function processorLightningCSS(_?: ProcessorLightningCSSOptions): CSSProcessor;
// #endregion