/**
 * Generated by tsnapi — public API snapshot of `@unocss/autocomplete`
 */
// #region Interfaces
export interface AutocompleteOptions {
  matchType?: AutoCompleteMatchType;
  throwErrors?: boolean;
}
export interface AutocompleteTemplateGroup {
  type: 'group';
  values: string[];
}
export interface AutocompleteTemplateStatic {
  type: 'static';
  value: string;
}
export interface AutocompleteTemplateTheme {
  type: 'theme';
  objects: Record<string, unknown>[];
}
export interface ParsedAutocompleteTemplate {
  parts: AutocompleteTemplatePart[];
  suggest: (_: string, _?: AutoCompleteMatchType) => string[] | undefined;
  errors: AutocompleteParseError[];
}
export interface UnocssAutocomplete {
  suggest: (_: string, _?: boolean) => Promise<string[]>;
  suggestInFile: (_: string, _: number) => Promise<SuggestResult | undefined>;
  templates: (string | AutoCompleteFunction)[];
  cache: LRUCache<string, string[]>;
  errorCache: Map<string, AutocompleteParseError[]>;
  reset: () => void;
  enumerate: () => Promise<Set<string>>;
}
// #endregion

// #region Types
export type AutoCompleteMatchType = 'prefix' | 'fuzzy';
export type AutocompleteTemplatePart = AutocompleteTemplateStatic | AutocompleteTemplateGroup | AutocompleteTemplateTheme;
// #endregion

// #region Classes
export declare class AutocompleteParseError extends Error {
  readonly template?: string | undefined;
  constructor(_: string, _?: string | undefined);
  toString(): string;
}
// #endregion

// #region Functions
export declare function cartesian<T>(_: T[][]): T[][];
export declare function createAutocomplete(_: UnoGenerator, _?: AutocompleteOptions): UnocssAutocomplete;
export declare function parseAutocomplete(_: string, _?: any, _?: Record<string, string>): ParsedAutocompleteTemplate;
export declare function searchAttrKey(_: string, _: number): string | undefined;
export declare function searchUsageBoundary(_: string, _: number, _?: boolean): {
  content: string;
  start: number;
  end: number;
} | undefined;
// #endregion

// #region Variables
export declare const ignoredThemeKeys: string[];
export declare const shorthands: Record<string, string>;
// #endregion