/**
 * Generated by tsnapi — public API snapshot of `unocss/astro`
 */
// #region Default Export
declare function _default<Theme extends object>(_?: AstroIntegrationConfig<Theme>): AstroIntegration;
export default _default
// #endregion