/**
 * Generated by tsnapi — public API snapshot of `unocss/astro`
 */
// #region Default Export
export default function UnocssAstroIntegration<Theme extends object>(_?: AstroIntegrationConfig<Theme>): AstroIntegration;
// #endregion