/**
 * Generated by tsnapi — public API snapshot of `unocss`
 */
// #region Functions
export declare function defineConfig<T extends object = Theme>(_: UserConfig<T>): UserConfig<T>;
// #endregion

// #region Re-exports
export * from "@unocss/core";
// #endregion

// #region Other
export { presetAttributify }
export { presetIcons }
export { presetMini }
export { PresetMiniTheme }
export { presetTagify }
export { presetTypography }
export { presetUno }
export { PresetUnoTheme }
export { presetWebFonts }
export { presetWind }
export { presetWind3 }
export { PresetWind3Theme }
export { presetWind4 }
export { PresetWind4Theme }
export { PresetWindTheme }
export { transformerAttributifyJsx }
export { transformerCompileClass }
export { transformerDirectives }
export { transformerVariantGroup }
// #endregion