/**
 * Generated by tsnapi — public API snapshot of `unocss/preset-tagify`
 */
// #region Default Export
export default preset_tagify_default
// #endregion

// #region Re-exports
export * from "@unocss/preset-tagify";
// #endregion