/**
 * Generated by tsnapi — public API snapshot of `unocss/preset-uno`
 */
// #region Default Export
export default preset_uno_default
// #endregion

// #region Re-exports
export * from "@unocss/preset-uno";
// #endregion