/**
 * Generated by tsnapi — public API snapshot of `unocss/preset-attributify`
 */
// #region Default Export
export default preset_attributify_default
// #endregion

// #region Re-exports
export * from "@unocss/preset-attributify";
// #endregion