/**
 * Generated by tsnapi — public API snapshot of `unocss/rollup`
 */
// #region Default Export
declare function _default<Theme extends object>(_?: RollupPluginConfig<Theme> | string): Plugin;
export default _default
// #endregion

// #region Re-exports
export * from "@unocss/rollup";
// #endregion