/**
 * Generated by tsnapi — public API snapshot of `unocss/rollup`
 */
// #region Default Export
export default function UnocssRollupPlugin<Theme extends object>(_?: RollupPluginConfig<Theme> | string): Plugin;
// #endregion

// #region Re-exports
export * from "@unocss/rollup";
// #endregion