/**
 * Generated by tsnapi — public API snapshot of `unocss/vite`
 */
// #region Default Export
export default function UnocssVitePlugin<Theme extends object>(_?: VitePluginConfig<Theme> | string): Plugin[];
// #endregion

// #region Re-exports
export * from "@unocss/vite";
// #endregion