/**
 * Generated by tsnapi — public API snapshot of `unocss/vite`
 */
// #region Default Export
declare function _default<Theme extends object>(_?: VitePluginConfig<Theme> | string): Plugin[];
export default _default
// #endregion

// #region Re-exports
export * from "@unocss/vite";
// #endregion