/**
 * Generated by tsnapi — public API snapshot of `unocss/webpack`
 */
// #region Default Export
export default function UnocssWebpackPlugin<Theme extends object>(_?: WebpackPluginOptions<Theme> | string): WebpackPluginInstance;
// #endregion

// #region Re-exports
export * from "@unocss/webpack";
// #endregion