/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-mini/rules`
 */
// #region Functions
export declare function handlerBorderStyle([, a, s]: string[]): CSSEntries | undefined;
// #endregion

// #region Variables
export declare const alignments: StaticRule[];
export declare const appearance: Rule[];
export declare const appearances: Rule[];
export declare const aspectRatio: Rule[];
export declare const bgColors: Rule[];
export declare const borders: Rule[];
export declare const borderStyles: string[];
export declare const boxShadows: Rule<Theme>[];
export declare const boxShadowsBase: {
  '--un-ring-offset-shadow': string;
  '--un-ring-shadow': string;
  '--un-shadow-inset': string;
  '--un-shadow': string;
};
export declare const boxSizing: Rule[];
export declare const breaks: Rule[];
export declare const colorScheme: Rule[];
export declare const containerParent: Rule[];
export declare const contains: Rule[];
export declare const contents: Rule[];
export declare const contentVisibility: Rule[];
export declare const cssProperty: Rule[];
export declare const cssVariables: Rule[];
export declare const cursors: Rule[];
export declare const displays: Rule[];
export declare const fieldSizing: Rule[];
export declare const flex: Rule<Theme>[];
export declare const flexGridJustifiesAlignments: StaticRule[];
export declare const floats: Rule[];
export declare const fonts: Rule<Theme>[];
export declare const fontSmoothings: Rule[];
export declare const fontStyles: Rule[];
export declare const gaps: Rule[];
export declare const grids: Rule<Theme>[];
export declare const insets: Rule[];
export declare const justifies: StaticRule[];
export declare const margins: Rule[];
export declare const opacity: Rule[];
export declare const orders: Rule[];
export declare const outline: Rule<Theme>[];
export declare const overflows: Rule[];
export declare const paddings: Rule[];
export declare const placements: StaticRule[];
export declare const pointerEvents: Rule[];
export declare const positions: Rule[];
export declare const questionMark: Rule[];
export declare const resizes: Rule[];
export declare const ringBase: {
  '--un-ring-inset': string;
  '--un-ring-offset-width': string;
  '--un-ring-offset-color': string;
  '--un-ring-width': string;
  '--un-ring-color': string;
  '--un-shadow': string;
};
export declare const rings: Rule<Theme>[];
export declare const rules: Rule<Theme>[];
export declare const sizes: Rule<Theme>[];
export declare const svgUtilities: Rule<Theme>[];
export declare const tabSizes: Rule<Theme>[];
export declare const textAligns: Rule[];
export declare const textDecorations: Rule<Theme>[];
export declare const textIndents: Rule<Theme>[];
export declare const textOverflows: Rule[];
export declare const textShadows: Rule<Theme>[];
export declare const textStrokes: Rule<Theme>[];
export declare const textTransforms: Rule[];
export declare const textWraps: Rule[];
export declare const transformBase: { /* collapsed */ }
export declare const transforms: Rule[];
export declare const transitions: Rule<Theme>[];
export declare const userSelects: Rule[];
export declare const varEmpty: string;
export declare const verticalAligns: Rule[];
export declare const whitespaces: Rule[];
export declare const willChange: Rule[];
export declare const zIndexes: Rule[];
// #endregion