/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-mini/theme`
 */
// #region Interfaces
export interface Colors {
  [key: string]: Colors & {
    DEFAULT?: string;
  } | string;
}
export interface Theme {
  width?: Record<string, string>;
  height?: Record<string, string>;
  maxWidth?: Record<string, string>;
  maxHeight?: Record<string, string>;
  minWidth?: Record<string, string>;
  minHeight?: Record<string, string>;
  inlineSize?: Record<string, string>;
  blockSize?: Record<string, string>;
  maxInlineSize?: Record<string, string>;
  maxBlockSize?: Record<string, string>;
  minInlineSize?: Record<string, string>;
  minBlockSize?: Record<string, string>;
  borderRadius?: Record<string, string>;
  breakpoints?: Record<string, string>;
  verticalBreakpoints?: Record<string, string>;
  colors?: Colors;
  borderColor?: Colors;
  backgroundColor?: Colors;
  textColor?: Colors;
  shadowColor?: Colors;
  accentColor?: Colors;
  fontFamily?: Record<string, string>;
  fontSize?: Record<string, string | [string, string | CSSObject] | [string, string, string]>;
  fontWeight?: Record<string, string>;
  lineHeight?: Record<string, string>;
  letterSpacing?: Record<string, string>;
  wordSpacing?: Record<string, string>;
  boxShadow?: Record<string, string | string[]>;
  textIndent?: Record<string, string>;
  textShadow?: Record<string, string | string[]>;
  textStrokeWidth?: Record<string, string>;
  ringWidth?: Record<string, string>;
  lineWidth?: Record<string, string>;
  spacing?: Record<string, string>;
  duration?: Record<string, string>;
  aria?: Record<string, string>;
  data?: Record<string, string>;
  zIndex?: Record<string, string>;
  blur?: Record<string, string>;
  dropShadow?: Record<string, string | string[]>;
  easing?: Record<string, string>;
  transitionProperty?: Record<string, string>;
  media?: Record<string, string>;
  supports?: Record<string, string>;
  containers?: Record<string, string>;
  animation?: ThemeAnimation;
  gridAutoColumn?: Record<string, string>;
  gridAutoRow?: Record<string, string>;
  gridColumn?: Record<string, string>;
  gridRow?: Record<string, string>;
  gridTemplateColumn?: Record<string, string>;
  gridTemplateRow?: Record<string, string>;
  container?: {
    center?: boolean;
    padding?: string | Record<string, string>;
    maxWidth?: Record<string, string>;
  };
  preflightRoot?: Arrayable<string>;
  preflightBase?: Record<string, string | number>;
}
export interface ThemeAnimation {
  keyframes?: Record<string, string>;
  durations?: Record<string, string>;
  timingFns?: Record<string, string>;
  properties?: Record<string, object>;
  counts?: Record<string, string | number>;
  category?: Record<string, string>;
}
// #endregion

// #region Variables
export declare const baseSize: { /* collapsed */ }
export declare const blockSize: { /* collapsed */ }
export declare const blur: {
  DEFAULT: string;
  '0': string;
  sm: string;
  md: string;
  lg: string;
  xl: string;
  '2xl': string;
  '3xl': string;
};
export declare const borderRadius: {
  DEFAULT: string;
  none: string;
  sm: string;
  md: string;
  lg: string;
  xl: string;
  '2xl': string;
  '3xl': string;
  full: string;
};
export declare const boxShadow: {
  DEFAULT: string[];
  none: string;
  sm: string;
  md: string[];
  lg: string[];
  xl: string[];
  '2xl': string;
  inner: string;
};
export declare const breakpoints: {
  sm: string;
  md: string;
  lg: string;
  xl: string;
  '2xl': string;
};
export declare const colors: { /* collapsed */ }
export declare const containers: { /* collapsed */ }
export declare const dropShadow: {
  DEFAULT: string[];
  sm: string;
  md: string[];
  lg: string[];
  xl: string[];
  '2xl': string;
  none: string;
};
export declare const duration: {
  DEFAULT: string;
  none: string;
  75: string;
  100: string;
  150: string;
  200: string;
  300: string;
  500: string;
  700: string;
  1000: string;
};
export declare const fontFamily: {
  sans: string;
  serif: string;
  mono: string;
};
export declare const fontSize: Theme['fontSize'];
export declare const fontWeight: {
  thin: string;
  extralight: string;
  light: string;
  normal: string;
  medium: string;
  semibold: string;
  bold: string;
  extrabold: string;
  black: string;
};
export declare const height: { /* collapsed */ }
export declare const inlineSize: { /* collapsed */ }
export declare const letterSpacing: {
  tighter: string;
  tight: string;
  normal: string;
  wide: string;
  wider: string;
  widest: string;
};
export declare const lineHeight: {
  none: string;
  tight: string;
  snug: string;
  normal: string;
  relaxed: string;
  loose: string;
};
export declare const lineWidth: {
  DEFAULT: string;
  none: string;
};
export declare const maxBlockSize: { /* collapsed */ }
export declare const maxHeight: { /* collapsed */ }
export declare const maxInlineSize: { /* collapsed */ }
export declare const maxWidth: { /* collapsed */ }
export declare const media: {
  mouse: string;
};
export declare const preflightBase: { /* collapsed */ }
export declare const ringWidth: {
  DEFAULT: string;
  none: string;
};
export declare const spacing: { /* collapsed */ }
export declare const textIndent: Theme['textIndent'];
export declare const textShadow: {
  DEFAULT: string[];
  none: string;
  sm: string;
  md: string[];
  lg: string[];
  xl: string[];
};
export declare const textStrokeWidth: Theme['textStrokeWidth'];
export declare const theme: { /* collapsed */ }
export declare const verticalBreakpoints: {
  sm: string;
  md: string;
  lg: string;
  xl: string;
  '2xl': string;
};
export declare const width: { /* collapsed */ }
export declare const wordSpacing: {
  tighter: string;
  tight: string;
  normal: string;
  wide: string;
  wider: string;
  widest: string;
};
export declare const zIndex: {
  auto: string;
};
// #endregion