/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-mini/utils`
 */
// #region Namespaces
export declare namespace valueHandlers {
  export function auto(_: string): "auto" | undefined;
  export function bracket(_: string): string | undefined;
  export function bracketOfColor(_: string): string | undefined;
  export function bracketOfLength(_: string): string | undefined;
  export function bracketOfPosition(_: string): string | undefined;
  export function cssvar(_: string): string | undefined;
  export function degree(_: string): string | undefined;
  export function fraction(_: string): string | undefined;
  export function global(_: string): string | undefined;
  export function number(_: string): number | undefined;
  export function numberWithUnit(_: string): string | undefined;
  export function percent(_: string): string | undefined;
  export function position(_: string): string | undefined;
  export function properties(_: string): string | undefined;
  export function px(_: string): string | undefined;
  export function rem(_: string): string | undefined;
  export function time(_: string): string | undefined;
}
// #endregion

// #region Functions
export declare function colorableShadows(_: string | string[], _: string): string[];
export declare function colorResolver(_: string, _: string, _?: ThemeColorKeys, _?: (_: CSSObject) => boolean): DynamicMatcher;
export declare function directionSize(_: string): DynamicMatcher;
export declare function hasParseableColor(_: string | undefined, _: Theme, _: ThemeColorKeys): boolean;
export declare function isCSSMathFn(_: string | undefined): boolean;
export declare function isSize(_: string): boolean;
export declare function makeGlobalStaticRules(_: string, _?: string): StaticRule[];
export declare function parseColor(_: string, _: Theme, _?: ThemeColorKeys): ParsedColorValue | undefined;
export declare function resolveBreakpoints({ theme, generator }: Readonly<VariantContext<Theme>>, _?: 'breakpoints' | 'verticalBreakpoints'): {
  point: string;
  size: string;
}[] | undefined;
export declare function resolveVerticalBreakpoints(_: Readonly<VariantContext<Theme>>): {
  point: string;
  size: string;
}[] | undefined;
export declare function splitShorthand(_: string, _: string): string[] | undefined;
export declare function transformXYZ(_: string, _: string, _: string): [string, string][];
// #endregion

// #region Variables
export declare const CONTROL_MINI_NO_NEGATIVE: string;
export declare const cornerMap: Record<string, string[]>;
export declare const cssMathFnRE: RegExp;
export declare const cssVarFnRE: RegExp;
export declare const directionMap: Record<string, string[]>;
export declare const globalKeywords: string[];
export declare const h: import("@unocss/rule-utils").ValueHandler<"number" | "auto" | "position" | "numberWithUnit" | "rem" | "px" | "percent" | "fraction" | "bracket" | "bracketOfColor" | "bracketOfLength" | "bracketOfPosition" | "cssvar" | "time" | "degree" | "global" | "properties", object>;
export declare const handler: import("@unocss/rule-utils").ValueHandler<"number" | "auto" | "position" | "numberWithUnit" | "rem" | "px" | "percent" | "fraction" | "bracket" | "bracketOfColor" | "bracketOfLength" | "bracketOfPosition" | "cssvar" | "time" | "degree" | "global" | "properties", object>;
export declare const insetMap: Record<string, string[]>;
export declare const positionMap: Record<string, string>;
export declare const xyzArray: string[];
export declare const xyzMap: Record<string, string[]>;
// #endregion

// #region Re-exports
export * from "@unocss/rule-utils";
// #endregion