/**
 * Generated by tsnapi — public API snapshot of `@unocss/preset-mini/variants`
 */
// #region Functions
export declare function variantBreakpoints(): VariantObject;
export declare function variantColorsMediaOrClass(_?: PresetMiniOptions): Variant[];
export declare function variantImportant(): VariantObject;
export declare function variantPseudoClassesAndElements(): VariantObject[];
export declare function variantPseudoClassFunctions(): VariantObject;
export declare function variants(_: PresetMiniOptions): Variant<Theme>[];
export declare function variantTaggedAriaAttributes(_?: PresetMiniOptions): Variant[];
export declare function variantTaggedDataAttributes(_?: PresetMiniOptions): Variant[];
export declare function variantTaggedPseudoClasses(_?: PresetMiniOptions): VariantObject[];
// #endregion

// #region Variables
export declare const variantAria: VariantObject;
export declare const variantChildren: Variant[];
export declare const variantCombinators: Variant[];
export declare const variantContainerQuery: VariantObject;
export declare const variantCssLayer: Variant;
export declare const variantCustomMedia: VariantObject;
export declare const variantDataAttribute: VariantObject;
export declare const variantInternalLayer: Variant;
export declare const variantLanguageDirections: Variant[];
export declare const variantNegative: Variant;
export declare const variantPartClasses: VariantObject;
export declare const variantPrint: VariantObject;
export declare const variantScope: Variant;
export declare const variantSelector: Variant;
export declare const variantStartingStyle: Variant;
export declare const variantSupports: VariantObject;
export declare const variantTheme: Variant;
export declare const variantVariables: Variant;
// #endregion