/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContentExample: typeof import('./.vitepress/theme/components/ContentExample.vue')['default']
    ContentExamples: typeof import('./.vitepress/theme/components/ContentExamples.vue')['default']
    ContentIntegrations: typeof import('./.vitepress/theme/components/ContentIntegrations.vue')['default']
    HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
    LinkGrid: typeof import('./.vitepress/theme/components/LinkGrid.vue')['default']
    RainbowAnimationSwitcher: typeof import('./.vitepress/theme/components/RainbowAnimationSwitcher.vue')['default']
    RainbowSwitcher: typeof import('./.vitepress/theme/components/RainbowSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ContentExample: typeof import('./.vitepress/theme/components/ContentExample.vue')['default']
  const ContentExamples: typeof import('./.vitepress/theme/components/ContentExamples.vue')['default']
  const ContentIntegrations: typeof import('./.vitepress/theme/components/ContentIntegrations.vue')['default']
  const HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
  const LinkGrid: typeof import('./.vitepress/theme/components/LinkGrid.vue')['default']
  const RainbowAnimationSwitcher: typeof import('./.vitepress/theme/components/RainbowAnimationSwitcher.vue')['default']
  const RainbowSwitcher: typeof import('./.vitepress/theme/components/RainbowSwitcher.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}