/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContentExample: typeof import('./.vitepress/theme/components/ContentExample.vue')['default']
    ContentExamples: typeof import('./.vitepress/theme/components/ContentExamples.vue')['default']
    ContentIntegrations: typeof import('./.vitepress/theme/components/ContentIntegrations.vue')['default']
    HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
    LinkGrid: typeof import('./.vitepress/theme/components/LinkGrid.vue')['default']
    NavBarRainbowAnimation: typeof import('./.vitepress/theme/components/NavBarRainbowAnimation.vue')['default']
    NavScreenRainbowAnimation: typeof import('./.vitepress/theme/components/NavScreenRainbowAnimation.vue')['default']
    RainbowAnimation: typeof import('./.vitepress/theme/components/RainbowAnimation.vue')['default']
    RainbowAnimationSwitcher: typeof import('./.vitepress/theme/components/RainbowAnimationSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenRainbowAnimation: typeof import('./.vitepress/theme/components/ScreenRainbowAnimation.vue')['default']
    UnoCSSNavBar: typeof import('./.vitepress/theme/components/UnoCSSNavBar.vue')['default']
    UnoCSSNavBarExtra: typeof import('./.vitepress/theme/components/UnoCSSNavBarExtra.vue')['default']
    UnoCSSNavScreen: typeof import('./.vitepress/theme/components/UnoCSSNavScreen.vue')['default']
    UnoCSSRainbow: typeof import('./.vitepress/theme/components/UnoCSSRainbow.vue')['default']
    UnoCSSScreen: typeof import('./.vitepress/theme/components/UnoCSSScreen.vue')['default']
    UnoCSSSwitcher: typeof import('./.vitepress/theme/components/UnoCSSSwitcher.vue')['default']
    UnoCSSSwticher: typeof import('./.vitepress/theme/components/UnoCSSSwticher.vue')['default']
  }
}
