export const INCLUDE_COMMENT = '@unocss-include'
export const IGNORE_COMMENT = '@unocss-ignore'
export const INCLUDE_COMMENT_IDE = '@unocss-ide-include'
export const CSS_PLACEHOLDER = '@unocss-placeholder'
export const CSS_GLOBAL_PLACEHOLDER = '@unocss-global-placeholder'
