/**
 * Generated by tsnapi — public API snapshot of `@unocss/astro`
 */
// #region Interfaces
export interface AstroIntegrationConfig<Theme extends object = object> extends VitePluginConfig<Theme> {
  injectReset?: string | boolean;
  injectEntry?: boolean | string;
  injectExtra?: string[];
}
// #endregion

// #region Default Export
declare function _default<Theme extends object>(_?: AstroIntegrationConfig<Theme>, _?: UserConfigDefaults): AstroIntegration;
export default _default
// #endregion